"use client"

import { FormEvent, useEffect, useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import Navbar from "@/app/components/navbar"
import Sidebar from "@/app/components/sidebar"
import PageLoader from "@/app/components/page-loader"
import { useToast } from "@/app/components/toast-provider"
import { apiUrl } from "@/lib/api"

type Skill = { _id: string; skillName: string; defaultDailyWage?: number }
type Site = { _id: string; siteName: string; siteCode?: string; status: string }
type Api<T> = { success: boolean; data?: T; message?: string }
type Form = { name:string; mobile:string; gender:string; dob:string; aadhaarNumber:string; panNumber:string; address:string; skillId:string; siteId:string; dailyWage:string; bankAccountNumber:string; ifscCode:string; emergencyContactName:string; emergencyContactRelation:string; emergencyContactMobile:string; joiningDate:string; resignationDate:string; isPFApplicable:boolean; pfUanNumber:string; isESICApplicable:boolean; esicIpNumber:string }
const initial:Form={name:"",mobile:"",gender:"",dob:"",aadhaarNumber:"",panNumber:"",address:"",skillId:"",siteId:"",dailyWage:"",bankAccountNumber:"",ifscCode:"",emergencyContactName:"",emergencyContactRelation:"",emergencyContactMobile:"",joiningDate:new Date().toISOString().slice(0,10),resignationDate:"",isPFApplicable:false,pfUanNumber:"",isESICApplicable:false,esicIpNumber:""}
const input="mt-2 h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm font-normal outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"
const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="block text-[11px] font-semibold text-slate-700">{label}{children}</label>
const Section=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="border-b border-slate-100 pb-3 text-sm font-bold text-slate-900">{title}</h2>{children}</section>

export default function CreateLabourPage(){
 const router=useRouter(),{showToast}=useToast(); const [form,setForm]=useState(initial),[skills,setSkills]=useState<Skill[]>([]),[sites,setSites]=useState<Site[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false); const [photo,setPhoto]=useState<File|null>(null)
 useEffect(()=>{const controller=new AbortController();Promise.all([fetch(apiUrl("/skills/get-skilles"),{credentials:"include",signal:controller.signal}),fetch(apiUrl("/sites/get-sites"),{credentials:"include",signal:controller.signal})]).then(async([a,b])=>{const x=await a.json() as Api<Skill[]>,y=await b.json() as Api<Site[]>;if(!a.ok||!x.success)throw new Error(x.message||"Skills could not be loaded");if(!b.ok||!y.success)throw new Error(y.message||"Sites could not be loaded");setSkills(x.data||[]);setSites((y.data||[]).filter(s=>s.status==="ACTIVE"))}).catch(e=>{if(e.name!=="AbortError")showToast(e.message,"error")}).finally(()=>setLoading(false));return()=>controller.abort()},[showToast])
 const set=(key:keyof Form,value:string|boolean)=>setForm(current=>({...current,[key]:value}))
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);try{const data=new FormData();Object.entries(form).forEach(([key,value])=>data.append(key,String(value)));if(photo)data.append("photo",photo);const response=await fetch(apiUrl("/labours/create"),{method:"POST",credentials:"include",body:data});const result=await response.json() as Api<unknown>;if(!response.ok||!result.success)throw new Error(result.message||"Labour could not be registered");showToast(result.message||"Labour registered successfully","success");router.push("/pages/contractorpages/labours");router.refresh()}catch(e){showToast(e instanceof Error?e.message:"Labour could not be registered","error")}finally{setSaving(false)}}
 if(loading)return <PageLoader label="Loading sites and skills" fullScreen />
 return <div className="flex min-h-screen bg-[#f7f8fc]"><Sidebar/><div className="min-w-0 flex-1"><Navbar/><main className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-7"><header className="mb-5"><p className="text-xs text-slate-500">Labours / <span className="text-indigo-600">Add Labour</span></p><h1 className="mt-2 text-2xl font-bold">Add Labour Registration</h1><p className="mt-1 text-sm text-slate-500">Employee code and QR code will be generated automatically.</p></header>
 <form onSubmit={submit} className="space-y-5">
  <Section title="Photo & Personal Details"><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Photo (JPG/PNG/WEBP, max 2 MB)"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)} className={`${input} py-2`}/></Field><Field label="Full Name *"><input required value={form.name} onChange={e=>set("name",e.target.value)} className={input}/></Field><Field label="Mobile *"><input required inputMode="numeric" pattern="[0-9]+" value={form.mobile} onChange={e=>set("mobile",e.target.value.replace(/\D/g,""))} className={input}/></Field><Field label="Gender *"><select required value={form.gender} onChange={e=>set("gender",e.target.value)} className={input}><option value="">Select</option><option value="MALE">Male</option><option value="FEMALE">Female</option><option value="OTHER">Other</option></select></Field><Field label="Date of Birth"><input type="date" value={form.dob} onChange={e=>set("dob",e.target.value)} className={input}/></Field><Field label="Aadhaar"><input inputMode="numeric" pattern="[0-9]{12}" maxLength={12} value={form.aadhaarNumber} onChange={e=>set("aadhaarNumber",e.target.value.replace(/\D/g,"").slice(0,12))} className={input}/></Field><Field label="PAN"><input pattern="[A-Za-z]{5}[0-9]{4}[A-Za-z]" maxLength={10} value={form.panNumber} onChange={e=>set("panNumber",e.target.value.toUpperCase())} className={input}/></Field><Field label="Address"><input value={form.address} onChange={e=>set("address",e.target.value)} className={input}/></Field></div></Section>
  <Section title="Employment & Skills"><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Primary Skill *"><select required value={form.skillId} onChange={e=>{const id=e.target.value,w=skills.find(s=>s._id===id)?.defaultDailyWage;setForm(f=>({...f,skillId:id,dailyWage:w?.toString()||""}))}} className={input}><option value="">Select Skill</option>{skills.map(s=><option key={s._id} value={s._id}>{s.skillName}</option>)}</select></Field><Field label="Site *"><select required value={form.siteId} onChange={e=>set("siteId",e.target.value)} className={input}><option value="">Select Site</option>{sites.map(s=><option key={s._id} value={s._id}>{s.siteName}</option>)}</select></Field><Field label="Daily Wage"><input type="number" min="0" value={form.dailyWage} onChange={e=>set("dailyWage",e.target.value)} className={input}/></Field><Field label="Joining Date *"><input required type="date" value={form.joiningDate} onChange={e=>set("joiningDate",e.target.value)} className={input}/></Field><Field label="Resignation Date"><input type="date" min={form.joiningDate} value={form.resignationDate} onChange={e=>set("resignationDate",e.target.value)} className={input}/></Field></div></Section>
  <Section title="Bank & Emergency Contact"><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Bank Account"><input inputMode="numeric" pattern="[0-9]{9,18}" maxLength={18} value={form.bankAccountNumber} onChange={e=>set("bankAccountNumber",e.target.value.replace(/\D/g,""))} className={input}/></Field><Field label="IFSC"><input pattern="[A-Za-z]{4}0[A-Za-z0-9]{6}" maxLength={11} value={form.ifscCode} onChange={e=>set("ifscCode",e.target.value.toUpperCase())} className={input}/></Field><Field label="Emergency Contact Name"><input value={form.emergencyContactName} onChange={e=>set("emergencyContactName",e.target.value)} className={input}/></Field><Field label="Relation"><input value={form.emergencyContactRelation} onChange={e=>set("emergencyContactRelation",e.target.value)} className={input}/></Field><Field label="Emergency Mobile"><input inputMode="numeric" pattern="[0-9]{10}" maxLength={10} value={form.emergencyContactMobile} onChange={e=>set("emergencyContactMobile",e.target.value.replace(/\D/g,""))} className={input}/></Field></div></Section>
  <Section title="UAN & ESIC"><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isPFApplicable} onChange={e=>set("isPFApplicable",e.target.checked)}/> PF Applicable</label>{form.isPFApplicable&&<Field label="UAN Number *"><input required inputMode="numeric" pattern="[0-9]{12}" maxLength={12} value={form.pfUanNumber} onChange={e=>set("pfUanNumber",e.target.value.replace(/\D/g,"").slice(0,12))} className={input}/></Field>}</div><div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isESICApplicable} onChange={e=>set("isESICApplicable",e.target.checked)}/> ESIC Applicable</label>{form.isESICApplicable&&<Field label="ESIC Number *"><input required inputMode="numeric" pattern="[0-9]{10}" maxLength={10} value={form.esicIpNumber} onChange={e=>set("esicIpNumber",e.target.value.replace(/\D/g,"").slice(0,10))} className={input}/></Field>}</div></div></Section>
  <div className="flex justify-end gap-3"><Link href="/pages/contractorpages/labours" className="rounded-md border bg-white px-6 py-3 text-sm font-semibold">Cancel</Link><button disabled={saving} className="rounded-md bg-indigo-700 px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving...":"Save Labour"}</button></div>
 </form></main></div></div>
}
