"use client"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import Navbar from "@/app/components/navbar"
import Sidebar from "@/app/components/sidebar"
import { useToast } from "@/app/components/toast-provider"
import { apiUrl } from "@/lib/api"
type Site={_id:string;siteName:string;siteCode:string;clientName:string;status:string}
type LabourDetail={labourId:string|null;labourName:string;labourCode:string;presentDays:number;halfDays:number;holidayDays:number;overtimeHours:number;labourAmount:number;overtimeAmount:number;totalAmount:number}
type InvoiceLine={description:string;hsnSacCode:string;quantity:number;rate:number;amount:number}
type Preview={invoiceNumber:string;site:Site;attendanceCount:number;labourCount:number;labourDetails:LabourDetail[];lines:InvoiceLine[];baseAmount:number}
type Api<T>={success:boolean;data?:T;message?:string}
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2})
const dateValue=(date:Date)=>date.toISOString().slice(0,10)
export default function GenerateInvoicePage(){
 const router=useRouter(),{showToast}=useToast()
 const [initialDates]=useState(()=>{const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1),due=new Date(now);due.setDate(due.getDate()+15);return{from:dateValue(monthStart),to:dateValue(now),due:dateValue(due)}})
 const [sites,setSites]=useState<Site[]>([]),[siteId,setSiteId]=useState(""),[billingFrom,setBillingFrom]=useState(initialDates.from),[billingTo,setBillingTo]=useState(initialDates.to),[dueDate,setDueDate]=useState(initialDates.due),[serviceChargePercent,setService]=useState("0"),[gstPercent,setGst]=useState("18"),[adjustmentAmount,setAdjustment]=useState("0"),[notes,setNotes]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false)
 useEffect(()=>{fetch(apiUrl("/sites/get-sites"),{credentials:"include"}).then(r=>r.json()).then((x:Api<Site[]>)=>setSites((x.data||[]).filter(s=>s.status==="ACTIVE"))).catch(()=>showToast("Sites could not be loaded.","error"))},[showToast])
 const loadPreview=async()=>{if(!siteId){showToast("Select a site first.","error");return}setLoading(true);try{const p=new URLSearchParams({siteId,billingFrom,billingTo}),r=await fetch(apiUrl("/site-invoices/preview?"+p),{credentials:"include"}),x=await r.json() as Api<Preview>;if(!r.ok||!x.success||!x.data)throw new Error(x.message||"Preview failed.");setPreview(x.data)}catch(e){showToast(e instanceof Error?e.message:"Preview failed.","error")}finally{setLoading(false)}}
 const totals=useMemo(()=>{const base=preview?.baseAmount||0,service=base*Number(serviceChargePercent||0)/100,taxable=Math.max(base+service+Number(adjustmentAmount||0),0),gst=taxable*Number(gstPercent||0)/100;return{service,taxable,gst,total:taxable+gst}},[preview,serviceChargePercent,adjustmentAmount,gstPercent])
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!preview){showToast("Generate preview before creating invoice.","error");return}setSaving(true);try{const r=await fetch(apiUrl("/site-invoices"),{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({siteId,billingFrom,billingTo,dueDate,serviceChargePercent:Number(serviceChargePercent),gstPercent:Number(gstPercent),adjustmentAmount:Number(adjustmentAmount),notes})}),x=await r.json() as Api<{_id:string;invoiceNumber:string}>;if(!r.ok||!x.success)throw new Error(x.message||"Invoice could not be created.");showToast(`Invoice ${x.data?.invoiceNumber||""} created successfully.`,"success");router.push("/pages/contractorpages/invoices")}catch(e){showToast(e instanceof Error?e.message:"Invoice creation failed.","error")}finally{setSaving(false)}}
 return <div className="flex h-screen overflow-hidden bg-[#f7f8fc]"><Sidebar/><div className="flex min-w-0 flex-1 flex-col overflow-hidden"><Navbar/><main className="min-h-0 flex-1 overflow-y-auto p-5 lg:p-7"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs text-slate-500">Invoices / <span className="font-semibold text-indigo-600">Generate</span></p><h1 className="mt-2 text-2xl font-bold">Generate Site Invoice</h1><p className="mt-1 text-sm text-slate-500">Create a verified invoice from site attendance, wages and overtime.</p></div><Link href="/pages/contractorpages/invoices" className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-600">View Invoices</Link></header>
 <form onSubmit={submit} className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-5"><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="border-b pb-3 text-sm font-bold">Billing Period</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600 md:col-span-2">Site *<select required value={siteId} onChange={e=>{setSiteId(e.target.value);setPreview(null)}} className="mt-2 h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">Select active site</option>{sites.map(s=><option key={s._id} value={s._id}>{s.siteName} - {s.clientName}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Billing From *<input required type="date" value={billingFrom} onChange={e=>{setBillingFrom(e.target.value);setPreview(null)}} className="mt-2 h-11 w-full rounded-md border border-slate-300 px-3"/></label><label className="text-xs font-semibold text-slate-600">Billing To *<input required type="date" value={billingTo} onChange={e=>{setBillingTo(e.target.value);setPreview(null)}} className="mt-2 h-11 w-full rounded-md border border-slate-300 px-3"/></label></div><button type="button" onClick={loadPreview} disabled={loading} className="mt-4 h-10 rounded-md bg-indigo-700 px-5 text-sm font-semibold text-white disabled:opacity-50">{loading?"Calculating...":"Calculate Invoice Preview"}</button></section>
 <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="text-sm font-bold">Attendance Billing Details</h2><span className="text-xs text-slate-400">{preview?preview.labourCount+" labours / "+preview.attendanceCount+" records":"No preview"}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-[9px] uppercase text-slate-500"><tr>{["Labour","Present","Half Day","Holiday","OT Hours","Labour Charge","OT Charge","Total"].map(h=><th key={h} className="border-b px-4 py-3">{h}</th>)}</tr></thead><tbody>{preview?.labourDetails.map((l,i)=><tr key={i} className="text-xs"><td className="border-b px-4 py-3"><strong>{l.labourName}</strong><span className="block text-[9px] text-slate-400">{l.labourCode}</span></td>{[l.presentDays,l.halfDays,l.holidayDays,l.overtimeHours].map((v,j)=><td key={j} className="border-b px-4 text-center">{v}</td>)}<td className="border-b px-4">{money.format(l.labourAmount)}</td><td className="border-b px-4">{money.format(l.overtimeAmount)}</td><td className="border-b px-4 font-bold">{money.format(l.totalAmount)}</td></tr>)}</tbody></table></div>{preview&&!preview.labourDetails.length&&<p className="p-10 text-center text-sm text-slate-500">No attendance found for selected site and period.</p>}</section></div>
 <aside className="h-fit space-y-5"><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="border-b pb-3 text-sm font-bold">Invoice Settings</h2><div className="mt-4 rounded-md border border-indigo-100 bg-indigo-50 p-3"><p className="text-[9px] font-bold uppercase tracking-wide text-indigo-500">Invoice Number</p><p className="mt-1 font-mono text-base font-bold text-indigo-800">{preview?.invoiceNumber||"Generated after preview"}</p><p className="mt-1 text-[9px] text-indigo-500">Generated automatically for the current financial year.</p></div><div className="mt-4 space-y-4"><label className="block text-xs font-semibold text-slate-600">Due Date<input required type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-slate-300 px-3"/></label><label className="block text-xs font-semibold text-slate-600">Service Charge %<input type="number" min="0" max="100" step="0.01" value={serviceChargePercent} onChange={e=>setService(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-slate-300 px-3"/></label><label className="block text-xs font-semibold text-slate-600">Adjustment (+/-)<input type="number" step="0.01" value={adjustmentAmount} onChange={e=>setAdjustment(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-slate-300 px-3"/></label><label className="block text-xs font-semibold text-slate-600">GST %<input type="number" min="0" max="100" step="0.01" value={gstPercent} onChange={e=>setGst(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-slate-300 px-3"/></label><label className="block text-xs font-semibold text-slate-600">Notes<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 w-full rounded-md border border-slate-300 p-3"/></label></div></section>
 <section className="rounded-lg bg-gradient-to-br from-indigo-700 to-violet-700 p-5 text-white shadow-sm"><h2 className="text-sm font-bold">Invoice Summary</h2><dl className="mt-4 divide-y divide-white/15 text-xs"><div className="flex justify-between py-2"><dt>Attendance & OT</dt><dd>{money.format(preview?.baseAmount||0)}</dd></div><div className="flex justify-between py-2"><dt>Service Charge</dt><dd>{money.format(totals.service)}</dd></div><div className="flex justify-between py-2"><dt>Adjustment</dt><dd>{money.format(Number(adjustmentAmount||0))}</dd></div><div className="flex justify-between py-2"><dt>Taxable</dt><dd>{money.format(totals.taxable)}</dd></div><div className="flex justify-between py-2"><dt>GST</dt><dd>{money.format(totals.gst)}</dd></div><div className="flex justify-between pt-4 text-base font-bold"><dt>Grand Total</dt><dd>{money.format(totals.total)}</dd></div></dl><button disabled={saving||!preview?.labourDetails.length} className="mt-5 h-11 w-full rounded-md bg-white font-bold text-indigo-700 disabled:opacity-50">{saving?"Creating Invoice...":"Create Invoice"}</button></section></aside></form></main></div></div>
}

