const router=require("express").Router();
const c=require("../controllers/superAdminController");
const control=require("../controllers/superAdminControlController");
const plans=require("../controllers/subscriptionPlanController");
const {verifyToken}=require("../middlewares/auth.middleware");
const {authorizeRoles}=require("../middlewares/role.middleware");
const {auditSuperAdminMutation}=require("../middlewares/audit.middleware");
router.use(verifyToken,authorizeRoles("SUPER_ADMIN"));
router.use(auditSuperAdminMutation);
router.get("/dashboard",c.dashboard);
router.get("/data",c.platformResources);
router.get("/data/:resource",c.platformData);
router.get("/companies",c.listCompanies);
router.post("/companies",c.createCompany);
router.get("/companies/:id",c.getCompany);
router.put("/companies/:id",c.updateCompany);
router.patch("/companies/:id/status",c.companyStatus);
router.delete("/companies/:id",c.deleteCompany);
router.get("/users",c.listUsers);
router.get("/users/:id",c.getUser);
router.put("/users/:id",c.updateUser);
router.patch("/users/:id/status",c.userStatus);
router.delete("/users/:id",c.deleteUser);
router.get("/subscriptions/summary",control.subscriptionSummary);
router.get("/subscriptions",control.listSubscriptions);
router.post("/subscriptions",control.createSubscription);
router.put("/subscriptions/:id",control.updateSubscription);
router.patch("/subscriptions/:id/status",control.subscriptionStatus);
router.get("/subscriptions/:id/payment-proof",control.paymentProof);
router.patch("/subscriptions/:id/verify-payment",control.verifySubscriptionPayment);
router.delete("/subscriptions/:id",control.deleteSubscription);
router.get("/plans",plans.adminList);
router.post("/plans",plans.create);
router.put("/plans/:id",plans.update);
router.patch("/plans/:id/status",plans.status);
router.delete("/plans/:id",plans.remove);
router.get("/notifications/summary",control.notificationSummary);
router.get("/notifications",control.listNotifications);
router.post("/notifications",control.createNotification);
router.put("/notifications/:id",control.updateNotification);
router.patch("/notifications/read-all",control.markAllRead);
router.patch("/notifications/:id/read",control.markRead);
router.delete("/notifications/:id",control.deleteNotification);
router.get("/audit-logs",control.listAuditLogs);
router.get("/settings",control.getSettings);
router.put("/settings",control.updateSettings);
router.get("/reports/summary",control.reportSummary);
module.exports=router;




