"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import PageLoader from "./page-loader"
import { useToast } from "./toast-provider"
import { Pagination, superAdminApi } from "@/lib/super-admin"

type Row = Record<string, unknown> & { _id?: string }
type Company = { _id: string; companyName: string; companyCode: string }
export type ResourceColumn = { key: string; label: string; kind?: "money" | "date" | "status" | "boolean" | "month" }
export type ResourceMetric = { label: string; value: (rows: Row[], total: number) => string | number; tone: string; hint: string }
export type ResourcePageConfig = { resource: string; eyebrow: string; title: string; description: string; columns: ResourceColumn[]; metrics: ResourceMetric[]; statuses?: string[]; search?: boolean; period?: "date" | "month" | "none"; accent: string }

const objectLabel = (value: Record<string, unknown>) => String(value.companyName || value.name || value.siteName || value.skillName || value.employeeCode || value.invoiceNumber || value._id || "Details")
const format = (value: unknown, kind?: ResourceColumn["kind"]) => {
  if (value === null || value === undefined || value === "") return "-"
  if (kind === "money") return `â‚¹${Number(value).toLocaleString("en-IN")}`
  if (kind === "date") return new Date(String(value)).toLocaleDateString("en-IN")
  if (kind === "boolean") return value ? "Enabled" : "Disabled"
  if (kind === "month") return new Date(2000, Number(value) - 1).toLocaleString("en", { month: "short" })
  if (typeof value === "object") return objectLabel(value as Record<string, unknown>)
  return String(value).replace(/_/g, " ")
}
const valueAt = (row: Row, key: string) => key.split(".").reduce<unknown>((value, part) => value && typeof value === "object" ? (value as Record<string, unknown>)[part] : undefined, row)

export default function PlatformResourcePage({ config }: { config: ResourcePageConfig }) {
  const { showToast } = useToast()
  const [rows, setRows] = useState<Row[]>([]), [companies, setCompanies] = useState<Company[]>([]), [pagination, setPagination] = useState<Pagination | null>(null), [selected, setSelected] = useState<Row | null>(null)
  const [loading, setLoading] = useState(true), [page, setPage] = useState(1), [companyId, setCompanyId] = useState(""), [search, setSearch] = useState(""), [status, setStatus] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [month, setMonth] = useState(""), [year, setYear] = useState("")
  useEffect(() => { superAdminApi<Company[]>("/companies?limit=100").then((r) => setCompanies(r.data)).catch(() => undefined) }, [])
  const load = useCallback(async () => { setLoading(true); const q = new URLSearchParams({ page: String(page), limit: "20" }); [["companyId", companyId], ["search", config.search ? search : ""], ["status", status], ["from", from], ["to", to], ["month", month], ["year", year]].forEach(([key, value]) => { if (value) q.set(key, value) }); try { const result = await superAdminApi<Row[]>(`/data/${config.resource}?${q}`); setRows(result.data); setPagination(result.pagination || null) } catch (error) { showToast(error instanceof Error ? error.message : "Records could not load", "error") } finally { setLoading(false) } }, [companyId, config.resource, config.search, from, month, page, search, showToast, status, to, year])
  useEffect(() => { const id = setTimeout(() => void load(), 250); return () => clearTimeout(id) }, [load])
  const total = pagination?.total || rows.length
  const reset = () => { setCompanyId(""); setSearch(""); setStatus(""); setFrom(""); setTo(""); setMonth(""); setYear(""); setPage(1) }
  const detailEntries = useMemo(() => selected ? Object.entries(selected).filter(([key]) => !["_id", "__v", "isDeleted"].includes(key)) : [], [selected])
  return <div>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className={`text-sm font-bold ${config.accent}`}>{config.eyebrow}</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">{config.title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{config.description}</p></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">Read-only platform access</span></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{config.metrics.map((metric) => <article key={metric.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`h-2 w-10 rounded-full ${metric.tone}`} /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">{metric.label}</p><strong className="mt-2 block text-2xl font-black text-slate-900">{metric.value(rows, total)}</strong><p className="mt-1 text-xs text-slate-400">{metric.hint}</p></article>)}</section>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><select value={companyId} onChange={(e) => { setCompanyId(e.target.value); setPage(1) }} className="h-10 rounded-lg border border-slate-300 px-2 text-xs"><option value="">All companies</option>{companies.map((company) => <option key={company._id} value={company._id}>{company.companyCode} â€” {company.companyName}</option>)}</select>{config.search && <input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }} placeholder={`Search ${config.title.toLowerCase()}`} className="h-10 rounded-lg border border-slate-300 px-3 text-xs" />}{config.statuses?.length && <select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }} className="h-10 rounded-lg border border-slate-300 px-2 text-xs"><option value="">All statuses</option>{config.statuses.map((item) => <option key={item}>{item}</option>)}</select>}{config.period === "date" && <><input aria-label="From date" type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="h-10 rounded-lg border border-slate-300 px-2 text-xs" /><input aria-label="To date" type="date" value={to} onChange={(e) => setTo(e.target.value)} className="h-10 rounded-lg border border-slate-300 px-2 text-xs" /></>}{config.period === "month" && <><select value={month} onChange={(e) => setMonth(e.target.value)} className="h-10 rounded-lg border border-slate-300 px-2 text-xs"><option value="">All months</option>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{new Date(2000, index).toLocaleString("en", { month: "long" })}</option>)}</select><input type="number" value={year} onChange={(e) => setYear(e.target.value)} placeholder="Year" className="h-10 rounded-lg border border-slate-300 px-3 text-xs" /></>}<button onClick={reset} className="h-10 rounded-lg border border-slate-300 px-4 text-xs font-bold text-slate-600 hover:bg-slate-50">Reset filters</button></div></section>
    <section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <PageLoader label={`Loading ${config.title}`} /> : <div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{config.columns.map((column) => <th key={column.key} className="px-4 py-3">{column.label}</th>)}<th className="px-4 py-3">Details</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => <tr key={row._id || index} className="hover:bg-slate-50">{config.columns.map((column) => { const value = valueAt(row, column.key); return <td key={column.key} className="max-w-56 truncate px-4 py-3" title={format(value, column.kind)}>{column.kind === "status" ? <span className="rounded-full bg-indigo-50 px-2.5 py-1 text-[10px] font-bold text-indigo-700">{format(value)}</span> : format(value, column.kind)}</td> })}<td className="px-4 py-3"><button onClick={() => setSelected(row)} className="group inline-flex items-center gap-2 rounded-lg border border-violet-200 bg-violet-50 px-3 py-2 text-xs font-bold text-violet-700 shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:bg-violet-600 hover:text-white hover:shadow-md"><svg aria-hidden="true" className="h-4 w-4" viewBox="0 0 24 24" fill="none"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" stroke="currentColor" strokeWidth="1.8"/><circle cx="12" cy="12" r="2.8" stroke="currentColor" strokeWidth="1.8"/></svg>View Details<span className="transition-transform group-hover:translate-x-0.5">→</span></button></td></tr>)}</tbody></table>{!rows.length && <div className="p-14 text-center"><p className="text-3xl">â–¦</p><p className="mt-2 font-bold text-slate-700">No records found</p><p className="text-sm text-slate-400">Try changing the selected filters.</p></div>}</div>}</section>
    {pagination && <footer className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>Showing {rows.length} of {pagination.total} records</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border bg-white px-3 py-1.5 disabled:opacity-40">Previous</button><span className="px-2">Page {page} of {pagination.pages || 1}</span><button disabled={page >= pagination.pages} onClick={() => setPage(page + 1)} className="rounded-lg border bg-white px-3 py-1.5 disabled:opacity-40">Next</button></div></footer>}
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/50" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null) }}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between border-b pb-5"><div><p className={`text-xs font-bold uppercase ${config.accent}`}>Complete record</p><h2 className="mt-1 text-2xl font-black text-slate-900">{config.title} Details</h2></div><button onClick={() => setSelected(null)} className="text-3xl text-slate-400">Ã—</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{detailEntries.map(([key, value]) => <div key={key} className={`${typeof value === "object" && value !== null ? "sm:col-span-2" : ""} rounded-xl border border-slate-200 bg-slate-50 p-4`}><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{key.replace(/([A-Z])/g, " $1")}</p>{typeof value === "object" && value !== null ? <pre className="mt-2 overflow-x-auto whitespace-pre-wrap text-xs text-slate-700">{JSON.stringify(value, null, 2)}</pre> : <p className="mt-1 break-words text-sm font-semibold text-slate-800">{format(value, /date|At$/i.test(key) ? "date" : undefined)}</p>}</div>)}</div></aside></div>}
  </div>
}

