"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { apiUrl } from "@/lib/api"
import { superAdminApi } from "@/lib/super-admin"
export default function SuperAdminHeader() {
  const router = useRouter(), [name, setName] = useState("Super Admin"), [unread, setUnread] = useState(0)
  useEffect(() => { fetch(apiUrl("/auth/me"), { credentials: "include" }).then(r => r.json()).then(r => { if (r.user?.name) setName(r.user.name) }).catch(() => undefined); const load = () => superAdminApi<{ unread: number }>("/notifications/summary").then(r => setUnread(r.data.unread)).catch(() => undefined); load(); const id = window.setInterval(load, 30000); return () => window.clearInterval(id) }, [])
  const logout = async () => { await fetch(apiUrl("/auth/logout"), { method: "POST", credentials: "include" }); router.replace("/pages/login"); router.refresh() }
  return <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-6 backdrop-blur"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-600">Platform Administration</p><p className="text-sm text-slate-500">Manage every company and system record</p></div><div className="flex items-center gap-3"><Link href="/pages/superadmin/notifications" aria-label={`${unread} unread notifications`} className="relative flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 transition hover:border-violet-300 hover:bg-violet-50 hover:text-violet-700"><svg aria-hidden="true" className="h-5 w-5" viewBox="0 0 24 24" fill="none"><path d="M18 9a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>{unread>0&&<span className="absolute -right-1 -top-1 flex h-5 min-w-5 items-center justify-center rounded-full bg-red-500 px-1 text-[9px] font-black text-white">{unread>99?"99+":unread}</span>}</Link><span className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-violet-600 to-indigo-700 text-sm font-bold text-white">{name.slice(0,1).toUpperCase()}</span><div className="hidden sm:block"><p className="text-sm font-bold text-slate-800">{name}</p><p className="text-[10px] text-slate-500">SUPER ADMIN</p></div><button onClick={logout} className="ml-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:border-red-200 hover:bg-red-50 hover:text-red-600">Logout</button></div></header>
}
