"use client"
import Image from "next/image"
import Link from "next/link"
import { usePathname } from "next/navigation"
const main = [["dashboard","Dashboard","/pages/superadmin"],["companies","Companies","/pages/superadmin/companies"],["users","Users","/pages/superadmin/users"],["plans","Plan Catalog","/pages/superadmin/plans"],["subscriptions","Subscriptions","/pages/superadmin/subscriptions"],["notifications","Notifications","/pages/superadmin/notifications"],["data","Platform Data","/pages/superadmin/data"]] as const
const resources=["labours","sites","attendance","payments","salary-slips","salary-payments","invoices","skills","labour-sites","payroll-settings"]
const label=(value:string)=>value.replace(/-/g," ").replace(/\b\w/g,letter=>letter.toUpperCase())
const paths:Record<string,string>={dashboard:"M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z",companies:"M4 21V7l8-4 8 4v14M8 10h2m4 0h2M8 14h2m4 0h2M9 21v-3h6v3",users:"M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 21a8 8 0 0 1 16 0",plans:"M4 5h16v14H4zM8 3v4m8-4v4M7 11h10M7 15h6",subscriptions:"M3 6h18v13H3zM3 10h18M7 15h4",notifications:"M18 9a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4",data:"M4 5c0 1.7 3.6 3 8 3s8-1.3 8-3-3.6-3-8-3-8 1.3-8 3Zm0 0v7c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 12v7c0 1.7 3.6 3 8 3s8-1.3 8-3v-7"}
function Icon({name}:{name:string}){return <svg aria-hidden="true" className="h-5 w-5" viewBox="0 0 24 24" fill="none"><path d={paths[name]} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export default function SuperAdminSidebar(){const pathname=usePathname();return <aside className="sticky top-0 h-screen w-72 shrink-0 overflow-y-auto border-r border-slate-800 bg-[#0b1120] text-slate-300"><div className="border-b border-white/10 p-4"><Link href="/pages/superadmin" className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.04] p-3"><span className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-white shadow-lg"><Image src="/assets/logo.png?v=super-admin-clean" alt="Kinetic LMS" width={54} height={54} unoptimized className="h-[52px] w-[52px] object-contain"/></span><span><strong className="block text-lg text-white">Kinetic <i className="not-italic text-violet-400">LMS</i></strong><small className="font-bold uppercase tracking-[.18em] text-slate-500">Super Admin</small></span></Link></div><nav className="p-4"><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Control Center</p><ul className="space-y-1">{main.map(([id,name,href])=>{const active=href==="/pages/superadmin"?pathname===href:pathname===href||pathname.startsWith(href+"/");return <li key={href}><Link href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition ${active?"bg-violet-600 text-white shadow-lg shadow-violet-950/40":"hover:bg-white/[.06] hover:text-white"}`}><span className={`flex h-9 w-9 items-center justify-center rounded-lg ${active?"bg-white/15":"bg-white/[.05] text-slate-400"}`}><Icon name={id}/></span>{name}</Link></li>})}</ul><p className="mt-7 px-3 pb-2 text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Cross-company records</p><ul className="space-y-0.5">{resources.map(resource=>{const href=`/pages/superadmin/data/${resource}`,active=pathname===href;return <li key={resource}><Link href={href} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-xs transition ${active?"bg-violet-500/15 font-semibold text-violet-300":"text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-md ${active?"bg-violet-500/20":"bg-white/[.04]"}`}><svg aria-hidden="true" className="h-3.5 w-3.5" viewBox="0 0 20 20" fill="none"><path d="M4 4h12v12H4zM7 7h6M7 10h6M7 13h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg></span>{label(resource)}</Link></li>})}</ul></nav></aside>}
