"use client"

import { useMemo, useState } from "react"
import PageLoader from "@/app/components/page-loader"
import { apiUrl } from "@/lib/api"
import { useToast } from "@/app/components/toast-provider"
import { Filters, money, pad, ReportPage, type Salary } from "../_components/report-ui"
import { useReportData } from "../_components/use-report-data"

type Slip = Salary & { _id?: string; month?: number; year?: number; basicSalary?: number; hra?: number; otherAllowance?: number; bonus?: number; incentive?: number; overtimeAmount?: number; employeePF?: number; employeeESIC?: number; advance?: number; otherDeduction?: number; totalDeduction?: number; finalNetSalary?: number; employerPF?: number; employerESIC?: number; isFinalized?: boolean }
type Api<T> = { success: boolean; data?: T; message?: string }

export default function SalarySlipsPage() {
  const now = new Date(), { showToast } = useToast()
  const [month, setMonth] = useState(`${now.getFullYear()}-${pad(now.getMonth() + 1)}`)
  const [siteId, setSiteId] = useState(""), [query, setQuery] = useState(""), [selected, setSelected] = useState<Slip | null>(null), [working, setWorking] = useState("")
  const { salaries, sites, labourMap, loading } = useReportData(month)
  const [yearNumber, monthNumber] = month.split("-").map(Number)
  const rows = useMemo(() => (salaries as Slip[]).filter((salary) => { const labour = labourMap.get(salary.labourId), search = query.trim().toLowerCase(); return (!siteId || labour?.site?._id === siteId) && (!search || [salary.name, salary.mobile, labour?.labourCode].some((value) => String(value || "").toLowerCase().includes(search))) }), [salaries, labourMap, query, siteId])
  const value = (slip: Slip, modern: keyof Slip, legacy?: keyof Slip) => Number(slip[modern] ?? (legacy ? slip[legacy] : 0) ?? 0)

  async function openSlip(salary: Slip) {
    if (salary._id) { setSelected(salary); return }
    setWorking(salary.labourId)
    try { const response = await fetch(apiUrl("/salary/generate-slip"), { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ labourId: salary.labourId, month: monthNumber, year: yearNumber }) }); const result: Api<Slip> = await response.json(); if (!response.ok || !result.success || !result.data) throw new Error(result.message || "Salary slip could not be generated"); setSelected({ ...salary, ...result.data, labourId: salary.labourId, name: salary.name, mobile: salary.mobile }); showToast("Salary slip generated", "success") } catch (error) { showToast(error instanceof Error ? error.message : "Salary slip could not be generated", "error") } finally { setWorking("") }
  }

  async function download(format: "pdf" | "excel") {
    if (!selected?._id) return
    setWorking(format)
    try { const response = await fetch(apiUrl(`/salary/slip/${selected._id}/${format}`), { credentials: "include" }); if (!response.ok) { const error = await response.json().catch(() => null) as { message?: string } | null; throw new Error(error?.message || `${format.toUpperCase()} download failed`) } const url = URL.createObjectURL(await response.blob()), anchor = document.createElement("a"); anchor.href = url; anchor.download = `SalarySlip_${labourMap.get(selected.labourId)?.labourCode || selected.name}_${month}.` + (format === "pdf" ? "pdf" : "xlsx"); anchor.click(); URL.revokeObjectURL(url); showToast(`Salary slip ${format === "pdf" ? "PDF" : "Excel"} downloaded`, "success") } catch (error) { showToast(error instanceof Error ? error.message : "Download failed", "error") } finally { setWorking("") }
  }

  if (loading) return <PageLoader label="Loading salary slips" fullScreen />
  return <ReportPage title="Salary Slips" description="Kisi bhi labour ki monthly salary slip generate karke PDF ya Excel me download karein.">
    <Filters month={month} setMonth={setMonth} siteId={siteId} setSiteId={setSiteId} sites={sites}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search labour..." className="h-10 min-w-56 flex-1 rounded-md border border-slate-300 px-3 text-sm" /></Filters>
    <section className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{["Labour","Site","Gross Salary","Deductions","Net Salary","Paid","Balance","Status","Action"].map((heading) => <th key={heading} className="border-b px-4 py-3">{heading}</th>)}</tr></thead><tbody>{rows.map((salary) => { const labour = labourMap.get(salary.labourId); return <tr key={salary.labourId} className="hover:bg-slate-50"><td className="border-b px-4 py-3"><strong className="block text-xs">{salary.name}</strong><span className="text-[9px] text-slate-400">{labour?.labourCode || salary.mobile}</span></td><td className="border-b px-4 text-xs">{labour?.site?.siteName || "No site"}</td><td className="border-b px-4 font-semibold">{money.format(salary.grossSalary || 0)}</td><td className="border-b px-4 font-semibold text-red-600">{money.format(value(salary, "totalDeduction"))}</td><td className="border-b px-4 font-bold text-emerald-700">{money.format(value(salary, "finalNetSalary", "netSalary"))}</td><td className="border-b px-4">{money.format(salary.paidAmount || 0)}</td><td className="border-b px-4">{money.format(salary.balanceAmount || 0)}</td><td className="border-b px-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold">{salary.status}</span></td><td className="border-b px-4"><button disabled={working === salary.labourId} onClick={() => openSlip(salary)} className="rounded-md bg-indigo-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{working === salary.labourId ? "Generating..." : salary._id ? "View Slip" : "Generate Slip"}</button></td></tr> })}</tbody></table></div>{!rows.length && <div className="p-12 text-center text-sm text-slate-500">Selected month ke salary records nahi mile.</div>}</section>
    {selected && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><div className="mx-auto max-w-3xl rounded-xl bg-white shadow-2xl"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><b>Salary Slip Preview</b><div className="flex gap-2"><button disabled={Boolean(working)} onClick={() => download("pdf")} className="rounded-md bg-red-600 px-4 py-2 text-xs font-bold text-white">Download PDF</button><button disabled={Boolean(working)} onClick={() => download("excel")} className="rounded-md bg-emerald-600 px-4 py-2 text-xs font-bold text-white">Download Excel</button><button onClick={() => setSelected(null)} className="rounded-md border px-4 py-2 text-xs">Close</button></div></div><article className="p-8 text-sm text-slate-900"><h1 className="text-center text-2xl font-black">SALARY SLIP</h1><p className="mt-1 text-center text-slate-500">{new Date(yearNumber, monthNumber - 1).toLocaleDateString("en-IN", { month: "long", year: "numeric" })}</p><div className="mt-6 grid grid-cols-2 gap-3 rounded-lg border p-4"><p><b>Labour:</b> {selected.name}</p><p><b>Code:</b> {labourMap.get(selected.labourId)?.labourCode || "-"}</p><p><b>Mobile:</b> {selected.mobile}</p><p><b>Site:</b> {labourMap.get(selected.labourId)?.site?.siteName || "No site"}</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><SlipSection title="Earnings" rows={[["Basic Salary",value(selected,"basicSalary")],["HRA",value(selected,"hra")],["Other Allowance",value(selected,"otherAllowance")],["Bonus",value(selected,"bonus")],["Incentive",value(selected,"incentive")],["Overtime",value(selected,"overtimeAmount")],["Gross Salary",selected.grossSalary]]}/><SlipSection title="Deductions" rows={[["Employee PF",value(selected,"employeePF","pfEmployee")],["Employee ESIC",value(selected,"employeeESIC","esicEmployee")],["Advance",value(selected,"advance")],["Other Deduction",value(selected,"otherDeduction")],["Total Deduction",value(selected,"totalDeduction")],["Net Salary",value(selected,"finalNetSalary","netSalary")]]}/><SlipSection title="Employer Contribution" rows={[["Employer PF",value(selected,"employerPF","pfEmployer")],["Employer ESIC",value(selected,"employerESIC","esicEmployer")],["CTC",selected.ctc]]}/><SlipSection title="Payment" rows={[["Paid Amount",selected.paidAmount],["Balance",selected.balanceAmount]]}/></div><p className="mt-8 text-center text-xs text-slate-400">This is a system-generated salary slip.</p></article></div></div>}
  </ReportPage>
}

function SlipSection({ title, rows }: { title: string; rows: [string, number][] }) { return <section className="rounded-lg border"><h2 className="border-b bg-slate-50 px-4 py-3 font-bold">{title}</h2><dl className="divide-y">{rows.map(([label, amount]) => <div key={label} className="flex justify-between px-4 py-2"><dt className="text-slate-500">{label}</dt><dd className="font-semibold">{money.format(Number(amount || 0))}</dd></div>)}</dl></section> }
