"use client"
import { FormEvent, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import Navbar from "@/app/components/navbar"
import Sidebar from "@/app/components/sidebar"
import { apiUrl } from "@/lib/api"
import { useToast } from "@/app/components/toast-provider"
type Site={_id:string;siteName:string;siteCode?:string;clientName?:string}
type Item={description:string;unit:string;quantity:string;rate:string}
type Api<T>={success:boolean;data?:T;message?:string}
const today=new Date().toISOString().slice(0,10)
const after=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"})
const units=["Nos","Sq Ft","Sq M","Running Ft","Running M","Meter","Feet","Inch","Kg","Quintal","Ton","Liter","Cubic Ft","Cubic M","Bag","Box","Set","Point","Day","Hour","Month","Lump Sum"]
export default function GenerateQuotation(){
 const router=useRouter(),{showToast}=useToast()
 const [sites,setSites]=useState<Site[]>([]),[saving,setSaving]=useState(false)
 const [form,setForm]=useState({siteId:"",subject:"",issueDate:today,validUntil:after(30),discountPercent:"0",gstPercent:"18",notes:"",terms:"Rates are valid until the validity date. Work will begin after written approval.",status:"DRAFT"})
 const [items,setItems]=useState<Item[]>([{description:"",unit:"Nos",quantity:"1",rate:""}])
 useEffect(()=>{fetch(apiUrl("/sites/get-sites"),{credentials:"include"}).then(r=>r.json()).then((r:Api<Site[]>)=>{if(r.success)setSites(r.data||[])})},[])
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.rate)||0),0),[items])
 const taxable=subtotal-subtotal*(Number(form.discountPercent)||0)/100,total=taxable+taxable*(Number(form.gstPercent)||0)/100
 const changeItem=(index:number,key:keyof Item,value:string)=>setItems(items.map((item,i)=>i===index?{...item,[key]:value}:item))
 async function submit(e:FormEvent,status:string){e.preventDefault();setSaving(true);try{const response=await fetch(apiUrl("/quotations"),{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,status,items:items.map(i=>({...i,quantity:Number(i.quantity),rate:Number(i.rate)}))})});const result:Api<unknown>=await response.json();if(!response.ok||!result.success)throw new Error(result.message||"Quotation could not be created");showToast(result.message||"Quotation created","success");router.push("/pages/contractorpages/quotations")}catch(error){showToast(error instanceof Error?error.message:"Quotation could not be created","error")}finally{setSaving(false)}}
 return <div className="flex min-h-screen bg-slate-50"><Sidebar/><div className="min-w-0 flex-1"><Navbar/><main className="p-6">
  <header className="mb-6 flex items-end justify-between"><div><p className="text-xs font-semibold text-indigo-600">Quotations / New</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Create Work Quotation</h1><p className="mt-1 text-sm text-slate-500">Prepare an item-wise price proposal for a site.</p></div><Link href="/pages/contractorpages/quotations" className="rounded-md border bg-white px-4 py-2 text-sm font-semibold">Cancel</Link></header>
  <form onSubmit={e=>submit(e,form.status)} className="grid gap-5 xl:grid-cols-[1fr_320px]"><div className="space-y-5">
   <section className="grid gap-4 rounded-xl border bg-white p-5 shadow-sm sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Site *<select required value={form.siteId} onChange={e=>setForm({...form,siteId:e.target.value})} className="mt-2 h-11 w-full rounded-md border px-3 text-sm"><option value="">Select site</option>{sites.map(s=><option key={s._id} value={s._id}>{s.siteName} {s.clientName?"- "+s.clientName:""}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Subject / Work title *<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Civil and electrical work" className="mt-2 h-11 w-full rounded-md border px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Quotation date<input type="date" required value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})} className="mt-2 h-11 w-full rounded-md border px-3"/></label><label className="text-xs font-semibold text-slate-600">Valid until *<input type="date" min={form.issueDate} required value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})} className="mt-2 h-11 w-full rounded-md border px-3"/></label></section>
   <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Scope of work</h2><p className="mt-1 text-xs text-slate-500">Amount is calculated as Quantity × Rate per selected unit.</p></div><button type="button" onClick={()=>setItems([...items,{description:"",unit:"Nos",quantity:"1",rate:""}])} className="rounded-md bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">+ Add item</button></div><div className="space-y-3">{items.map((item,index)=><div key={index} className="grid gap-2 rounded-lg border bg-slate-50 p-3 md:grid-cols-[minmax(180px,1fr)_110px_90px_115px_125px_36px]"><input required value={item.description} onChange={e=>changeItem(index,"description",e.target.value)} placeholder="Particular / work description" className="h-10 rounded-md border px-3 text-sm"/><select required aria-label="Unit" value={item.unit} onChange={e=>changeItem(index,"unit",e.target.value)} className="h-10 rounded-md border bg-white px-2 text-sm">{units.map(unit=><option key={unit} value={unit}>{unit}</option>)}</select><input type="number" min=".01" step=".01" required value={item.quantity} onChange={e=>changeItem(index,"quantity",e.target.value)} placeholder="Qty" aria-label="Quantity" className="h-10 rounded-md border px-2 text-sm"/><input type="number" min="0" step=".01" required value={item.rate} onChange={e=>changeItem(index,"rate",e.target.value)} placeholder="Rate ₹" aria-label="Rate per unit" className="h-10 rounded-md border px-2 text-sm"/><div className="flex h-10 items-center justify-end rounded-md border bg-white px-2 text-sm font-bold text-slate-700" title="Quantity × Rate">{money.format((Number(item.quantity)||0)*(Number(item.rate)||0))}</div><button type="button" aria-label="Remove item" disabled={items.length===1} onClick={()=>setItems(items.filter((_,i)=>i!==index))} className="text-xl text-red-500 disabled:opacity-30">×</button></div>)}</div></section>
   <section className="grid gap-4 rounded-xl border bg-white p-5 shadow-sm sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={4} className="mt-2 w-full rounded-md border p-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Terms & conditions<textarea value={form.terms} onChange={e=>setForm({...form,terms:e.target.value})} rows={4} className="mt-2 w-full rounded-md border p-3 text-sm"/></label></section>
  </div><aside className="h-fit rounded-xl border bg-white p-5 shadow-sm xl:sticky xl:top-5"><h2 className="font-bold">Quotation total</h2><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Discount %<input type="number" min="0" max="100" value={form.discountPercent} onChange={e=>setForm({...form,discountPercent:e.target.value})} className="mt-2 h-10 w-full rounded-md border px-3"/></label><label className="text-xs font-semibold text-slate-600">GST %<input type="number" min="0" max="100" value={form.gstPercent} onChange={e=>setForm({...form,gstPercent:e.target.value})} className="mt-2 h-10 w-full rounded-md border px-3"/></label></div><dl className="mt-5 space-y-3 border-t pt-4 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{money.format(subtotal)}</dd></div><div className="flex justify-between"><dt>Taxable</dt><dd>{money.format(taxable)}</dd></div><div className="flex justify-between text-lg font-bold text-indigo-700"><dt>Total</dt><dd>{money.format(total)}</dd></div></dl><button disabled={saving} type="submit" className="mt-5 w-full rounded-md bg-indigo-700 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving...":"Save Draft"}</button><button disabled={saving} type="button" onClick={e=>submit(e as unknown as FormEvent,"SENT")} className="mt-2 w-full rounded-md border border-indigo-600 py-3 text-sm font-bold text-indigo-700 disabled:opacity-50">Save & Mark Sent</button></aside>
  </form></main></div></div>
}
