"use client"
import { useMemo, useState } from "react"
import { BarChart, DonutChart, Filters, money, ReportActions, number, pad, ReportPage, Stat } from "../_components/report-ui"
import { useReportData } from "../_components/use-report-data"
export default function WorkforceReportPage(){
 const now=new Date(),[month,setMonth]=useState(`${now.getFullYear()}-${pad(now.getMonth()+1)}`),[siteId,setSiteId]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("")
 const {labours,sites,loading}=useReportData(month)
 const rows=useMemo(()=>labours.filter(l=>{const q=query.trim().toLowerCase();return(!siteId||l.site?._id===siteId)&&(!status||l.status===status)&&(!q||[l.name,l.labourCode,l.mobile,l.skillId?.skillName].some(v=>(v||"").toLowerCase().includes(q)))}),[labours,query,siteId,status])
 const avg=rows.length?rows.reduce((s,l)=>s+Number(l.finalDailyWage||l.dailyWage||0),0)/rows.length:0
 const siteItems=sites.map(s=>({label:s.siteName,value:rows.filter(l=>l.site?._id===s._id).length,color:"bg-indigo-500"})).filter(i=>i.value)
 const skills=[...new Set(rows.map(l=>l.skillId?.skillName||"Unspecified"))].map(skill=>({label:skill,value:rows.filter(l=>(l.skillId?.skillName||"Unspecified")===skill).length,color:"bg-sky-500"}))
 return <ReportPage title="Workforce Report" description="Labour strength, status, skill mix, site allocation aur wage profile."><Filters month={month} setMonth={setMonth} siteId={siteId} setSiteId={setSiteId} sites={sites}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search labour or skill..." className="h-10 min-w-52 flex-1 rounded-md border border-slate-300 px-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-md border border-slate-300 bg-white px-3 text-sm"><option value="">All Status</option><option>ACTIVE</option><option>INACTIVE</option><option>BLOCKED</option></select><ReportActions title="Workforce Report" fileName={"Workforce_Report_"+month} tableId="workforce-report-table" /></Filters>
 <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Total Labour" value={number.format(rows.length)}/><Stat label="Active" value={rows.filter(l=>l.status==="ACTIVE").length} tone="text-emerald-700"/><Stat label="Inactive" value={rows.filter(l=>l.status==="INACTIVE").length} tone="text-amber-700"/><Stat label="Blocked" value={rows.filter(l=>l.status==="BLOCKED").length} tone="text-red-600"/><Stat label="Average Daily Wage" value={money.format(avg)} tone="text-indigo-700"/></section>
 <section className="mt-5 grid gap-5 xl:grid-cols-2"><BarChart title="Site-wise Workforce" items={siteItems}/><DonutChart title="Skill Distribution" items={skills.map((s,i)=>({...s,color:["#4f46e5","#0ea5e9","#10b981","#f59e0b","#8b5cf6","#ef4444"][i%6]}))}/></section>
 <section className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table id="workforce-report-table" className="w-full min-w-[1100px] border-collapse text-left"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{["Labour","Mobile","Site","Skill","Gender","Daily Wage","PF / UAN","ESIC / IP","Status"].map(h=><th key={h} className="border-b border-r border-slate-200 px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(l=><tr key={l._id} className="hover:bg-slate-50"><td className="border-b px-4 py-3"><strong className="block text-xs">{l.name}</strong><span className="text-[9px] text-slate-400">{l.labourCode}</span></td><td className="border-b px-4 text-xs">{l.mobile}</td><td className="border-b px-4 text-xs">{l.site?.siteName||"Unassigned"}</td><td className="border-b px-4 text-xs">{l.skillId?.skillName||"-"}</td><td className="border-b px-4 text-xs">{l.gender||"-"}</td><td className="border-b px-4 text-xs font-semibold">{money.format(Number(l.finalDailyWage||l.dailyWage||0))}</td><td className="border-b px-4 text-xs"><strong className={l.isPFApplicable && l.pfUanNumber ? "text-indigo-700" : "text-slate-400"}>{l.isPFApplicable && l.pfUanNumber ? l.pfUanNumber : "Not applicable"}</strong></td><td className="border-b px-4 text-xs"><strong className={l.isESICApplicable && l.esicIpNumber ? "text-sky-700" : "text-slate-400"}>{l.isESICApplicable && l.esicIpNumber ? l.esicIpNumber : "Not applicable"}</strong></td><td className="border-b px-4"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${l.status==="ACTIVE"?"bg-emerald-100 text-emerald-700":l.status==="BLOCKED"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{l.status}</span></td></tr>)}</tbody></table></div>{loading&&<p className="p-8 text-center text-sm text-slate-400">Loading report...</p>}</section>
 </ReportPage>
}

