"use client"
import { useMemo, useState } from "react"
import { BarChart, DonutChart, Filters, number, ReportActions, pad, refId, ReportPage, Stat } from "../_components/report-ui"
import { useReportData } from "../_components/use-report-data"
export default function AttendanceReportPage(){
 const now=new Date(),[month,setMonth]=useState(`${now.getFullYear()}-${pad(now.getMonth()+1)}`),[siteId,setSiteId]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("")
 const {attendance,labours,sites,labourMap,loading}=useReportData(month)
 const rows=useMemo(()=>attendance.filter(e=>{const l=labourMap.get(refId(e.labourId)),q=query.trim().toLowerCase();return(!siteId||refId(e.siteId)===siteId)&&(!status||e.status===status)&&(!q||[l?.name,l?.labourCode,l?.mobile].some(v=>(v||"").toLowerCase().includes(q)))}),[attendance,labourMap,query,siteId,status])
 const count=(s:string)=>rows.filter(e=>e.status===s).length,ot=rows.reduce((s,e)=>s+Number(e.overtimeHours||0),0),unique=new Set(rows.map(e=>refId(e.labourId))).size
 const labourRows=labours.filter(l=>!siteId||l.site?._id===siteId).map(l=>{const r=rows.filter(e=>refId(e.labourId)===l._id);return{labour:l,p:r.filter(e=>e.status==="PRESENT").length,a:r.filter(e=>e.status==="ABSENT").length,h:r.filter(e=>e.status==="HALF_DAY").length,leave:r.filter(e=>e.status==="LEAVE").length,ph:r.filter(e=>e.status==="HOLIDAY").length,ot:r.reduce((s,e)=>s+Number(e.overtimeHours||0),0)}}).filter(r=>!query.trim()||[r.labour.name,r.labour.labourCode,r.labour.mobile].some(v=>v.toLowerCase().includes(query.toLowerCase())))
 return <ReportPage title="Attendance Report" description="Labour-wise attendance, absence, leave, paid holiday aur overtime analysis."><Filters month={month} setMonth={setMonth} siteId={siteId} setSiteId={setSiteId} sites={sites}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search labour..." className="h-10 min-w-52 flex-1 rounded-md border border-slate-300 px-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-md border border-slate-300 bg-white px-3 text-sm"><option value="">All Status</option>{["PRESENT","ABSENT","HALF_DAY","LEAVE","HOLIDAY"].map(s=><option key={s}>{s}</option>)}</select><ReportActions title="Attendance Report" fileName={"Attendance_Report_"+month} tableId="attendance-report-table" /></Filters>
 <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Stat label="Labours Marked" value={number.format(unique)}/><Stat label="Present" value={count("PRESENT")} tone="text-emerald-600"/><Stat label="Absent" value={count("ABSENT")} tone="text-red-600"/><Stat label="Half Day" value={count("HALF_DAY")} tone="text-amber-600"/><Stat label="Paid Holiday" value={count("HOLIDAY")} tone="text-violet-600"/><Stat label="OT Hours" value={ot} tone="text-cyan-600"/></section>
 <section className="mt-5 grid gap-5 xl:grid-cols-2"><DonutChart title="Attendance Status Distribution" items={[{label:"Present",value:count("PRESENT"),color:"#10b981"},{label:"Absent",value:count("ABSENT"),color:"#ef4444"},{label:"Half Day",value:count("HALF_DAY"),color:"#f59e0b"},{label:"Leave",value:count("LEAVE"),color:"#0ea5e9"},{label:"Holiday",value:count("HOLIDAY"),color:"#8b5cf6"}]}/><BarChart title="Top Overtime Hours" items={labourRows.sort((a,b)=>b.ot-a.ot).slice(0,8).map(r=>({label:r.labour.name,value:r.ot,color:"bg-cyan-500"}))}/></section>
 <section className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table id="attendance-report-table" className="w-full min-w-[900px] border-collapse text-left"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{["Labour","Site","Present","Absent","Half Day","Leave","Paid Holiday","OT Hours"].map(h=><th key={h} className="border-b border-r border-slate-200 px-4 py-3">{h}</th>)}</tr></thead><tbody>{labourRows.map(r=><tr key={r.labour._id} className="hover:bg-slate-50"><td className="border-b px-4 py-3"><strong className="block text-xs">{r.labour.name}</strong><span className="text-[9px] text-slate-400">{r.labour.labourCode}</span></td><td className="border-b px-4 text-xs">{r.labour.site?.siteName||"No site"}</td>{[r.p,r.a,r.h,r.leave,r.ph,r.ot].map((v,i)=><td key={i} className="border-b px-4 text-center text-xs font-semibold">{v}</td>)}</tr>)}</tbody></table></div>{loading&&<p className="p-8 text-center text-sm text-slate-400">Loading report...</p>}</section>
 </ReportPage>
}
