"use client"
import { useMemo, useState } from "react"
import { BarChart, DonutChart, Filters, money, ReportActions, pad, ReportPage, Stat } from "../_components/report-ui"
import { useReportData } from "../_components/use-report-data"
const shown=(s:{status:string;balanceAmount:number;netSalary:number})=>s.balanceAmount>0?"PENDING":s.netSalary>0?"PAID":s.status
export default function SalaryReportPage(){
 const now=new Date(),[month,setMonth]=useState(`${now.getFullYear()}-${pad(now.getMonth()+1)}`),[siteId,setSiteId]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("")
 const {salaries,sites,labourMap,loading}=useReportData(month)
 const rows=useMemo(()=>salaries.filter(s=>{const l=labourMap.get(s.labourId),q=query.trim().toLowerCase();return(!siteId||l?.site?._id===siteId)&&(!status||shown(s)===status)&&(!q||[s.name,s.mobile,l?.labourCode].some(v=>(v||"").toLowerCase().includes(q)))}),[salaries,labourMap,query,siteId,status])
 const sum=(k:"grossSalary"|"netSalary"|"ctc"|"paidAmount"|"balanceAmount")=>rows.reduce((a,r)=>a+Number(r[k]||0),0)
 return <ReportPage title="Salary Report" description="Monthly gross salary, net payable, CTC, paid amount aur pending balance report."><Filters month={month} setMonth={setMonth} siteId={siteId} setSiteId={setSiteId} sites={sites}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search labour..." className="h-10 min-w-52 flex-1 rounded-md border border-slate-300 px-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-md border border-slate-300 bg-white px-3 text-sm"><option value="">All Status</option><option>PAID</option><option>PENDING</option><option>DRAFT</option></select><ReportActions title="Salary Report" fileName={"Salary_Report_"+month} tableId="salary-report-table" /></Filters>
 <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Gross Salary" value={money.format(sum("grossSalary"))}/><Stat label="Net Salary" value={money.format(sum("netSalary"))} tone="text-emerald-700"/><Stat label="Total CTC" value={money.format(sum("ctc"))} tone="text-violet-700"/><Stat label="Paid" value={money.format(sum("paidAmount"))} tone="text-indigo-700"/><Stat label="Balance" value={money.format(sum("balanceAmount"))} tone="text-red-600"/></section>
 <section className="mt-5 grid gap-5 xl:grid-cols-2"><BarChart title="Salary Position" format={money.format} items={[{label:"Gross",value:sum("grossSalary"),color:"bg-sky-500"},{label:"Net",value:sum("netSalary"),color:"bg-emerald-500"},{label:"CTC",value:sum("ctc"),color:"bg-violet-500"},{label:"Paid",value:sum("paidAmount"),color:"bg-indigo-500"},{label:"Balance",value:sum("balanceAmount"),color:"bg-red-500"}]}/><DonutChart title="Payment Status" items={[{label:"Paid",value:rows.filter(r=>shown(r)==="PAID").length,color:"#10b981"},{label:"Pending",value:rows.filter(r=>shown(r)==="PENDING").length,color:"#ef4444"},{label:"Draft",value:rows.filter(r=>shown(r)==="DRAFT").length,color:"#f59e0b"}]}/></section>
 <section className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table id="salary-report-table" className="w-full min-w-[1550px] border-collapse text-left"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{["Labour","Site","Present","OT Hours","PF UAN","PF Wage","Employee PF","Employer PF","ESIC IP","Employee ESIC","Employer ESIC","Gross","Net Salary","CTC","Paid","Balance","Status"].map(h=><th key={h} className="border-b border-r border-slate-200 px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=>{const l=labourMap.get(r.labourId),st=shown(r);return <tr key={r.labourId} className="hover:bg-slate-50"><td className="border-b px-4 py-3"><strong className="block text-xs">{r.name}</strong><span className="text-[9px] text-slate-400">{l?.labourCode||r.mobile}</span></td><td className="border-b px-4 text-xs">{l?.site?.siteName||"No site"}</td><td className="border-b px-4 text-center text-xs">{r.presentDays}</td><td className="border-b px-4 text-center text-xs">{r.overtimeHours}</td><td className="border-b px-4 text-xs font-semibold text-indigo-700">{l?.isPFApplicable && l.pfUanNumber ? l.pfUanNumber : "N/A"}</td><td className="border-b px-4 text-xs font-semibold">{money.format(r.pfWage || 0)}</td><td className="border-b px-4 text-xs font-semibold">{money.format(r.pfEmployee || 0)}</td><td className="border-b px-4 text-xs font-semibold">{money.format(r.pfEmployer || 0)}</td><td className="border-b px-4 text-xs font-semibold text-sky-700">{l?.isESICApplicable && l.esicIpNumber ? l.esicIpNumber : "N/A"}</td><td className="border-b px-4 text-xs font-semibold">{money.format(r.esicEmployee || 0)}</td><td className="border-b px-4 text-xs font-semibold">{money.format(r.esicEmployer || 0)}</td>{[r.grossSalary,r.netSalary,r.ctc,r.paidAmount,r.balanceAmount].map((v,i)=><td key={i} className="border-b px-4 text-xs font-semibold">{money.format(v)}</td>)}<td className="border-b px-4"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${st==="PAID"?"bg-emerald-100 text-emerald-700":st==="PENDING"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{st}</span></td></tr>})}</tbody></table></div>{loading&&<p className="p-8 text-center text-sm text-slate-400">Loading report...</p>}</section>
 </ReportPage>
}


