"use client"

import { FormEvent, useCallback, useEffect, useState } from "react"
import { useToast } from "@/app/components/toast-provider"
import PageLoader from "@/app/components/page-loader"
import { Pagination, Status, superAdminApi } from "@/lib/super-admin"

type Company = { _id: string; companyCode: string; companyName: string; ownerName: string; email: string; mobile: string; gstNumber?: string; status: Status; address: { street: string; city: string; state: string; pincode: string; country: string }; createdAt: string }
type Form = { companyName: string; ownerName: string; email: string; mobile: string; password: string; gstNumber: string; street: string; city: string; state: string; pincode: string; country: string }
const empty: Form = { companyName: "", ownerName: "", email: "", mobile: "", password: "", gstNumber: "", street: "", city: "", state: "", pincode: "", country: "India" }
const badge: Record<Status, string> = { ACTIVE: "bg-emerald-50 text-emerald-700", INACTIVE: "bg-amber-50 text-amber-700", BLOCKED: "bg-red-50 text-red-700" }

export default function CompaniesPage() {
  const { showToast } = useToast()
  const [rows, setRows] = useState<Company[]>([]), [pagination, setPagination] = useState<Pagination | null>(null)
  const [page, setPage] = useState(1), [search, setSearch] = useState(""), [status, setStatus] = useState("")
  const [loading, setLoading] = useState(true), [modal, setModal] = useState(false), [saving, setSaving] = useState(false)
  const [editing, setEditing] = useState<Company | null>(null), [form, setForm] = useState<Form>(empty), [detail, setDetail] = useState<(Company & { stats?: Record<string, unknown> }) | null>(null)
  const load = useCallback(async () => { setLoading(true); try { const q = new URLSearchParams({ page: String(page), limit: "15" }); if (search) q.set("search", search); if (status) q.set("status", status); const r = await superAdminApi<Company[]>(`/companies?${q}`); setRows(r.data); setPagination(r.pagination || null) } catch (e) { showToast(e instanceof Error ? e.message : "Companies could not load", "error") } finally { setLoading(false) } }, [page, search, status, showToast])
  useEffect(() => { const id = setTimeout(() => void load(), 250); return () => clearTimeout(id) }, [load])
  const openCreate = () => { setEditing(null); setForm(empty); setModal(true) }
  const openEdit = (c: Company) => { setEditing(c); setForm({ companyName: c.companyName, ownerName: c.ownerName, email: c.email, mobile: c.mobile, password: "", gstNumber: c.gstNumber || "", street: c.address?.street || "", city: c.address?.city || "", state: c.address?.state || "", pincode: c.address?.pincode || "", country: c.address?.country || "India" }); setModal(true) }
  const submit = async (e: FormEvent) => { e.preventDefault(); setSaving(true); const body = { companyName: form.companyName, ownerName: form.ownerName, email: form.email, mobile: form.mobile, ...(editing ? {} : { password: form.password }), gstNumber: form.gstNumber, address: { street: form.street, city: form.city, state: form.state, pincode: form.pincode, country: form.country } }; try { await superAdminApi(editing ? `/companies/${editing._id}` : "/companies", { method: editing ? "PUT" : "POST", body: JSON.stringify(body) }); showToast(editing ? "Company updated" : "Company and contractor created", "success"); setModal(false); load() } catch (e) { showToast(e instanceof Error ? e.message : "Save failed", "error") } finally { setSaving(false) } }
  const changeStatus = async (c: Company, next: Status) => { try { await superAdminApi(`/companies/${c._id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); showToast("Company status updated", "success"); load() } catch (e) { showToast(e instanceof Error ? e.message : "Status update failed", "error") } }
  const remove = async (c: Company) => { if (!confirm(`Delete ${c.companyName}? Company users will lose access.`)) return; try { await superAdminApi(`/companies/${c._id}`, { method: "DELETE" }); showToast("Company deleted", "success"); load() } catch (e) { showToast(e instanceof Error ? e.message : "Delete failed", "error") } }
  const view = async (id: string) => { try { const r = await superAdminApi<Company & { stats?: Record<string, unknown> }>(`/companies/${id}`); setDetail(r.data) } catch (e) { showToast(e instanceof Error ? e.message : "Details failed", "error") } }
  const field = "h-11 w-full rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100"
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-violet-600">Tenant Management</p><h1 className="mt-1 text-3xl font-black text-slate-950">Companies</h1><p className="mt-1 text-sm text-slate-500">Create companies and control complete tenant access.</p></div><button onClick={openCreate} className="rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-bold text-white">+ New Company</button></div>
    <div className="mt-6 flex flex-wrap gap-3 rounded-xl border border-slate-200 bg-white p-4"><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }} placeholder="Search name, code, email or mobile" className="h-10 min-w-64 flex-1 rounded-lg border border-slate-300 px-3 text-sm" /><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }} className="h-10 rounded-lg border border-slate-300 px-3 text-sm"><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option><option>BLOCKED</option></select></div>
    <div className="mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <PageLoader label="Loading companies" /> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Company", "Owner", "Contact", "Location", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((c) => <tr key={c._id} className="hover:bg-slate-50"><td className="px-4 py-4"><button onClick={() => view(c._id)} className="font-bold text-violet-700 hover:underline">{c.companyName}</button><small className="block text-slate-500">{c.companyCode}</small></td><td className="px-4 py-4">{c.ownerName}</td><td className="px-4 py-4"><span className="block">{c.email}</span><small>{c.mobile}</small></td><td className="px-4 py-4">{c.address?.city}, {c.address?.state}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${badge[c.status]}`}>{c.status}</span></td><td className="px-4 py-4"><div className="flex items-center gap-2 whitespace-nowrap"><button onClick={() => view(c._id)} title="View company details" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-violet-200 bg-violet-50 px-3 text-xs font-bold text-violet-700 transition hover:-translate-y-0.5 hover:bg-violet-600 hover:text-white">◉ <span>View</span></button><button onClick={() => openEdit(c)} title="Edit company" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-indigo-200 bg-indigo-50 px-3 text-xs font-bold text-indigo-700 transition hover:-translate-y-0.5 hover:bg-indigo-600 hover:text-white">✎ <span>Edit</span></button><label className="relative"><span className="sr-only">Change company status</span><select value={c.status} onChange={(e) => changeStatus(c, e.target.value as Status)} className="h-9 cursor-pointer appearance-none rounded-lg border border-slate-200 bg-white pl-3 pr-7 text-[10px] font-bold text-slate-700 shadow-sm outline-none transition hover:border-slate-400 focus:border-violet-500"><option>ACTIVE</option><option>INACTIVE</option><option>BLOCKED</option></select><span className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-slate-400">▼</span></label><button onClick={() => remove(c)} title="Delete company" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-red-200 bg-red-50 px-3 text-xs font-bold text-red-600 transition hover:-translate-y-0.5 hover:bg-red-600 hover:text-white">⌫ <span>Delete</span></button></div></td></tr>)}</tbody></table>{!rows.length && <p className="p-10 text-center text-slate-500">No companies found.</p>}</div>}</div>
    {pagination && <div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{pagination.total} companies</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Previous</button><span className="px-2 py-1.5">{page} / {pagination.pages || 1}</span><button disabled={page >= pagination.pages} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Next</button></div></div>}
    {modal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-black">{editing ? "Edit Company" : "Create Company"}</h2><p className="text-sm text-slate-500">{editing ? "Update tenant profile" : "Company and primary Contractor login will be created together."}</p></div><button type="button" onClick={() => setModal(false)} className="text-2xl">Ã—</button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{[["Company Name", "companyName"], ["Owner Name", "ownerName"], ["Email", "email"], ["Mobile", "mobile"], ["GST Number", "gstNumber"], ...(!editing ? [["Contractor Password", "password"]] : [])].map(([label, key]) => <label key={key} className="text-xs font-semibold text-slate-600">{label}<input required={!(["gstNumber"].includes(key))} type={key === "password" ? "password" : key === "email" ? "email" : "text"} minLength={key === "password" ? 8 : undefined} value={form[key as keyof Form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={`mt-1 ${field}`} /></label>)}</div><h3 className="mt-6 border-t pt-5 text-sm font-bold">Registered Address</h3><div className="mt-3 grid gap-4 md:grid-cols-2">{[["Street", "street"], ["City", "city"], ["State", "state"], ["PIN Code", "pincode"], ["Country", "country"]].map(([label, key]) => <label key={key} className="text-xs font-semibold text-slate-600">{label}<input required value={form[key as keyof Form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={`mt-1 ${field}`} /></label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setModal(false)} className="rounded-lg border px-4 py-2.5 text-sm font-bold">Cancel</button><button disabled={saving} className="rounded-lg bg-violet-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Save Company"}</button></div></form></div>}
    {detail && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">{detail.companyName}</h2><button onClick={() => setDetail(null)} className="text-2xl">Ã—</button></div><p className="text-sm text-slate-500">{detail.companyCode} â€¢ {detail.status}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-4"><small>Owner</small><strong className="block">{detail.ownerName}</strong></div><div className="rounded-lg bg-slate-50 p-4"><small>Contact</small><strong className="block text-sm">{detail.email}</strong><span>{detail.mobile}</span></div></div><h3 className="mt-5 font-bold">Complete Usage Statistics</h3><pre className="mt-2 max-h-64 overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-200">{JSON.stringify(detail.stats || {}, null, 2)}</pre></div></div>}
  </div>
}

