const fs=require("fs");
const Plan=require("../models/SubscriptionPlan"),Subscription=require("../models/Subscription"),SystemSetting=require("../models/SystemSetting");
const months={MONTHLY:1,QUARTERLY:3,HALF_YEARLY:6,YEARLY:12},safe=v=>new RegExp(String(v||"").replace(/[|\\{}()[\]^$+*?.-]/g,"\\$&"),"i");
exports.adminList=async(req,res)=>{try{const f={isDeleted:false};if(req.query.status)f.status=req.query.status;if(req.query.search){const r=safe(req.query.search);f.$or=[{name:r},{code:r},{tagline:r}]}res.json({success:true,data:await Plan.find(f).sort({sortOrder:1,price:1}).lean()})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.create=async(req,res)=>{try{const data=await Plan.create({...req.body,createdBy:req.user._id});res.status(201).json({success:true,message:"Subscription plan created",data})}catch(e){res.status(e.code===11000?409:400).json({success:false,message:e.code===11000?"Plan code already exists":e.message})}};
exports.update=async(req,res)=>{try{const data=await Plan.findOneAndUpdate({_id:req.params.id,isDeleted:false},{...req.body,updatedBy:req.user._id},{new:true,runValidators:true});if(!data)return res.status(404).json({success:false,message:"Plan not found"});res.json({success:true,message:"Subscription plan updated",data})}catch(e){res.status(e.code===11000?409:400).json({success:false,message:e.message})}};
exports.status=async(req,res)=>{try{if(!["DRAFT","PUBLISHED","ARCHIVED"].includes(req.body.status))return res.status(400).json({success:false,message:"Invalid plan status"});const data=await Plan.findOneAndUpdate({_id:req.params.id,isDeleted:false},{status:req.body.status,updatedBy:req.user._id},{new:true});if(!data)return res.status(404).json({success:false,message:"Plan not found"});res.json({success:true,message:"Plan status updated",data})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.remove=async(req,res)=>{try{const data=await Plan.findOneAndUpdate({_id:req.params.id,isDeleted:false},{isDeleted:true,status:"ARCHIVED",updatedBy:req.user._id},{new:true});if(!data)return res.status(404).json({success:false,message:"Plan not found"});res.json({success:true,message:"Plan archived"})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.publicPlans=async(_req,res)=>{try{res.json({success:true,data:await Plan.find({isDeleted:false,status:"PUBLISHED"}).select("-createdBy -updatedBy -isDeleted").sort({sortOrder:1,price:1}).lean()})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.paymentDetails=async(_req,res)=>{try{const keys=["paymentUpiId","paymentAccountName","paymentBankName","paymentAccountNumber","paymentIfsc","paymentInstructions"],rows=await SystemSetting.find({key:{$in:keys}}).lean(),values=Object.fromEntries(rows.map(row=>[row.key,row.value]));res.json({success:true,data:{upiId:values.paymentUpiId||process.env.PAYMENT_UPI_ID||"",accountName:values.paymentAccountName||process.env.PAYMENT_ACCOUNT_NAME||"",bankName:values.paymentBankName||process.env.PAYMENT_BANK_NAME||"",accountNumber:values.paymentAccountNumber||process.env.PAYMENT_ACCOUNT_NUMBER||"",ifsc:values.paymentIfsc||process.env.PAYMENT_IFSC||"",instructions:values.paymentInstructions||process.env.PAYMENT_INSTRUCTIONS||"Pay the exact plan amount, then upload the transaction screenshot."}})}catch(error){res.status(500).json({success:false,message:error.message})}};
exports.current=async(req,res)=>{try{const data=await Subscription.findOne({companyId:req.user.companyId,isDeleted:false}).select("-paymentProofPath").populate("planId","name code tagline status").lean();res.json({success:true,data:data?{...data,proofAvailable:!!data.paymentProofOriginalName}:null})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.subscribe=async(req,res)=>{try{const plan=await Plan.findOne({_id:req.body.planId,isDeleted:false,status:"PUBLISHED"}).lean();if(!plan)return res.status(404).json({success:false,message:"Plan is not available"});if(plan.price>0)return res.status(400).json({success:false,message:"Payment proof is required for this plan"});const start=new Date(),end=new Date(start);end.setMonth(end.getMonth()+(months[plan.billingCycle]||1));const set={planId:plan._id,planName:plan.name,planCode:plan.code,billingCycle:plan.billingCycle,amount:0,currency:plan.currency,startDate:start,endDate:end,trialEndsAt:plan.trialDays?new Date(Date.now()+plan.trialDays*86400000):null,status:plan.trialDays?"TRIAL":"ACTIVE",paymentStatus:"NOT_REQUIRED",verificationStatus:"APPROVED",verifiedAt:new Date(),verifiedBy:req.user._id,rejectionReason:"",autoRenew:true,limits:plan.limits,features:plan.features,updatedBy:req.user._id,isDeleted:false};let data=await Subscription.findOne({companyId:req.user.companyId});if(data){Object.assign(data,set);await data.save()}else data=await Subscription.create({...set,companyId:req.user.companyId,createdBy:req.user._id});res.json({success:true,message:"Free plan activated",data})}catch(e){res.status(400).json({success:false,message:e.message})}};

exports.submitPayment=async(req,res)=>{let createdFile=req.file?.path;try{if(!req.file)return res.status(400).json({success:false,message:"Payment screenshot or PDF is required"});const plan=await Plan.findOne({_id:req.body.planId,isDeleted:false,status:"PUBLISHED"}).lean();if(!plan)return res.status(404).json({success:false,message:"Plan is not available"});if(plan.price<=0)return res.status(400).json({success:false,message:"Use activate for a free plan"});const reference=String(req.body.paymentReference||"").trim();if(reference.length<4)return res.status(400).json({success:false,message:"Enter a valid transaction reference"});const existing=await Subscription.findOne({companyId:req.user.companyId});const previousProof=existing?.paymentProofPath;const now=new Date();const placeholderEnd=new Date(now);placeholderEnd.setMonth(placeholderEnd.getMonth()+(months[plan.billingCycle]||1));const set={planId:plan._id,planName:plan.name,planCode:plan.code,billingCycle:plan.billingCycle,amount:plan.price,currency:plan.currency,startDate:now,endDate:placeholderEnd,trialEndsAt:null,status:"SUSPENDED",paymentStatus:"PENDING",paymentReference:reference,paymentProofPath:req.file.path,paymentProofOriginalName:req.file.originalname,paymentProofMimeType:req.file.mimetype,verificationStatus:"PENDING",submittedAt:now,verifiedAt:null,verifiedBy:null,rejectionReason:"",autoRenew:false,limits:plan.limits,features:plan.features,updatedBy:req.user._id,isDeleted:false};let data;if(existing){Object.assign(existing,set);data=await existing.save()}else data=await Subscription.create({...set,companyId:req.user.companyId,createdBy:req.user._id});createdFile=null;if(previousProof&&previousProof!==data.paymentProofPath)fs.promises.unlink(previousProof).catch(()=>undefined);const safe=data.toObject();delete safe.paymentProofPath;res.status(201).json({success:true,message:"Payment submitted for Super Admin verification",data:{...safe,proofAvailable:true}})}catch(e){if(createdFile)fs.promises.unlink(createdFile).catch(()=>undefined);res.status(400).json({success:false,message:e.message})}};


