const fs = require("fs");
const path = require("path");
const { proofDirectory } = require("../middlewares/paymentProof.middleware");
const AuditLog = require("../models/AuditLog");
const SystemSetting = require("../models/SystemSetting");
const Attendance = require("../models/Attendance");
const Labour = require("../models/Labour");
const Site = require("../models/Site");
const SalarySlip = require("../models/SalarySlip");
const SiteInvoice = require("../models/SiteInvoice");
const Subscription=require("../models/Subscription"),Notification=require("../models/PlatformNotification"),Company=require("../models/Company");
const pages=q=>{const page=Math.max(1,+q.page||1),limit=Math.min(100,Math.max(1,+q.limit||20));return{page,limit,skip:(page-1)*limit}};
const result=(data,total,page,limit)=>({success:true,data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}),regex=v=>new RegExp(String(v||"").replace(/[|\\{}()[\]^$+*?.-]/g,"\\$&"),"i");
exports.subscriptionSummary=async(_q,res)=>{try{const now=new Date(),[total,active,trial,pastDue,pendingVerification,revenue]=await Promise.all([Subscription.countDocuments({isDeleted:false}),Subscription.countDocuments({isDeleted:false,status:"ACTIVE",endDate:{$gte:now}}),Subscription.countDocuments({isDeleted:false,status:"TRIAL"}),Subscription.countDocuments({isDeleted:false,status:{$in:["PAST_DUE","EXPIRED"]}}),Subscription.countDocuments({isDeleted:false,verificationStatus:"PENDING"}),Subscription.aggregate([{$match:{isDeleted:false,paymentStatus:"PAID"}},{$group:{_id:null,amount:{$sum:"$amount"}}}])]);res.json({success:true,data:{total,active,trial,pastDue,pendingVerification,revenue:revenue[0]?.amount||0}})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.listSubscriptions=async(req,res)=>{try{const{page,limit,skip}=pages(req.query),f={isDeleted:false};["status","paymentStatus","verificationStatus","companyId"].forEach(k=>{if(req.query[k])f[k]=req.query[k]});if(req.query.search){const r=regex(req.query.search),ids=await Company.find({$or:[{companyName:r},{companyCode:r}]}).distinct("_id");f.$or=[{planName:r},{planCode:r},{companyId:{$in:ids}}]}const[data,total]=await Promise.all([Subscription.find(f).populate("companyId","companyCode companyName status email mobile").sort({createdAt:-1}).skip(skip).limit(limit).lean(),Subscription.countDocuments(f)]);res.json(result(data.map(item=>{const safe={...item,proofAvailable:!!item.paymentProofPath};delete safe.paymentProofPath;return safe}),total,page,limit))}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.createSubscription=async(req,res)=>{try{if(await Subscription.exists({companyId:req.body.companyId,isDeleted:false}))return res.status(409).json({success:false,message:"Company already has a subscription"});const data=await Subscription.create({...req.body,createdBy:req.user._id});res.status(201).json({success:true,message:"Subscription created",data})}catch(e){res.status(400).json({success:false,message:e.message})}};
exports.updateSubscription=async(req,res)=>{try{const allowed=["planName","planCode","billingCycle","amount","currency","startDate","endDate","trialEndsAt","status","paymentStatus","paymentReference","autoRenew","limits","features","notes"],set={updatedBy:req.user._id};allowed.forEach(k=>{if(req.body[k]!==undefined)set[k]=req.body[k]});const data=await Subscription.findOneAndUpdate({_id:req.params.id,isDeleted:false},set,{new:true,runValidators:true});if(!data)return res.status(404).json({success:false,message:"Subscription not found"});res.json({success:true,message:"Subscription updated",data})}catch(e){res.status(400).json({success:false,message:e.message})}};
exports.subscriptionStatus=async(req,res)=>{try{if(!["TRIAL","ACTIVE","PAST_DUE","SUSPENDED","EXPIRED","CANCELLED"].includes(req.body.status))return res.status(400).json({success:false,message:"Invalid status"});const data=await Subscription.findOneAndUpdate({_id:req.params.id,isDeleted:false},{status:req.body.status,updatedBy:req.user._id},{new:true});if(!data)return res.status(404).json({success:false,message:"Subscription not found"});res.json({success:true,message:"Subscription status updated",data})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.deleteSubscription=async(req,res)=>{try{const data=await Subscription.findOneAndUpdate({_id:req.params.id,isDeleted:false},{isDeleted:true,status:"CANCELLED",updatedBy:req.user._id},{new:true});if(!data)return res.status(404).json({success:false,message:"Subscription not found"});res.json({success:true,message:"Subscription removed"})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.notificationSummary=async(req,res)=>{try{const[total,published,scheduled,unread]=await Promise.all([Notification.countDocuments({isDeleted:false}),Notification.countDocuments({isDeleted:false,status:"PUBLISHED"}),Notification.countDocuments({isDeleted:false,status:"SCHEDULED"}),Notification.countDocuments({isDeleted:false,status:"PUBLISHED",readBy:{$ne:req.user._id}})]);res.json({success:true,data:{total,published,scheduled,unread}})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.listNotifications=async(req,res)=>{try{const{page,limit,skip}=pages(req.query),f={isDeleted:false};["status","type","targetType"].forEach(k=>{if(req.query[k])f[k]=req.query[k]});if(req.query.search){const r=regex(req.query.search);f.$or=[{title:r},{message:r}]}const[data,total]=await Promise.all([Notification.find(f).populate("companyId","companyCode companyName").populate("userId","name employeeCode email").sort({createdAt:-1}).skip(skip).limit(limit).lean(),Notification.countDocuments(f)]);res.json(result(data.map(x=>({...x,isRead:x.readBy?.some(id=>String(id)===String(req.user._id))})),total,page,limit))}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.createNotification=async(req,res)=>{try{const{targetType="ALL",companyId,userId,role}=req.body;if(targetType==="COMPANY"&&!companyId)return res.status(400).json({success:false,message:"Select a company"});if(targetType==="USER"&&!userId)return res.status(400).json({success:false,message:"Select a user"});if(targetType==="ROLE"&&!role)return res.status(400).json({success:false,message:"Select a role"});const status=req.body.status==="SCHEDULED"?"SCHEDULED":"PUBLISHED",scheduledAt=status==="SCHEDULED"?new Date(req.body.scheduledAt):new Date();if(Number.isNaN(scheduledAt.getTime()))return res.status(400).json({success:false,message:"Valid schedule date and time is required"});if(status==="SCHEDULED"&&scheduledAt<=new Date())return res.status(400).json({success:false,message:"Schedule date and time must be in the future"});const data=await Notification.create({...req.body,status,scheduledAt,companyId:targetType==="COMPANY"?companyId:null,userId:targetType==="USER"?userId:null,role:targetType==="ROLE"?role:null,createdBy:req.user._id});res.status(201).json({success:true,message:status==="SCHEDULED"?"Notification scheduled":"Notification sent",data})}catch(e){res.status(400).json({success:false,message:e.message})}};
exports.updateNotification=async(req,res)=>{try{const allowed=["title","message","type","targetType","companyId","userId","role","actionLabel","actionUrl","scheduledAt","expiresAt","status"],set={};allowed.forEach(k=>{if(req.body[k]!==undefined)set[k]=req.body[k]});if(set.status==="SCHEDULED"){const scheduledAt=new Date(set.scheduledAt);if(Number.isNaN(scheduledAt.getTime()))return res.status(400).json({success:false,message:"Valid schedule date and time is required"});if(scheduledAt<=new Date())return res.status(400).json({success:false,message:"Schedule date and time must be in the future"});set.scheduledAt=scheduledAt}else if(set.status==="PUBLISHED")set.scheduledAt=new Date();const data=await Notification.findOneAndUpdate({_id:req.params.id,isDeleted:false},set,{new:true,runValidators:true});if(!data)return res.status(404).json({success:false,message:"Notification not found"});res.json({success:true,message:set.status==="SCHEDULED"?"Notification scheduled":"Notification updated",data})}catch(e){res.status(400).json({success:false,message:e.message})}};
exports.markRead=async(req,res)=>{try{const data=await Notification.findOneAndUpdate({_id:req.params.id,isDeleted:false},{$addToSet:{readBy:req.user._id}},{new:true});if(!data)return res.status(404).json({success:false,message:"Notification not found"});res.json({success:true,message:"Notification marked read"})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.markAllRead=async(req,res)=>{try{await Notification.updateMany({isDeleted:false,status:"PUBLISHED"},{$addToSet:{readBy:req.user._id}});res.json({success:true,message:"All notifications marked read"})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.deleteNotification=async(req,res)=>{try{const data=await Notification.findOneAndUpdate({_id:req.params.id,isDeleted:false},{isDeleted:true,status:"ARCHIVED"},{new:true});if(!data)return res.status(404).json({success:false,message:"Notification not found"});res.json({success:true,message:"Notification archived"})}catch(e){res.status(500).json({success:false,message:e.message})}};

exports.listAuditLogs = async (req, res) => { try {
  const page = Math.max(1, Number(req.query.page) || 1), limit = Math.min(100, Math.max(1, Number(req.query.limit) || 25));
  const filter = {}; if (req.query.resource) filter.resource = req.query.resource; if (req.query.action) filter.action = req.query.action;
  if (req.query.search) filter.$or = [{ actorName: new RegExp(req.query.search, "i") }, { path: new RegExp(req.query.search, "i") }];
  const [data, total] = await Promise.all([AuditLog.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), AuditLog.countDocuments(filter)]);
  res.json({ success: true, data, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
} catch (error) { res.status(500).json({ success: false, message: error.message }); } };

const settingDefaults = { platformName: "Kinetic LMS", supportEmail: "", timezone: "Asia/Kolkata", currency: "INR", maintenanceMode: false, requireStrongPasswords: true, sessionTimeoutMinutes: 480, documentExpiryAlertDays: 30, paymentUpiId: "", paymentAccountName: "", paymentBankName: "", paymentAccountNumber: "", paymentIfsc: "", paymentInstructions: "Pay the exact plan amount, then upload the transaction screenshot." };
exports.getSettings = async (req, res) => { try { const rows = await SystemSetting.find().lean(); const data = { ...settingDefaults }; rows.forEach((row) => { data[row.key] = row.value; }); res.json({ success: true, data }); } catch (error) { res.status(500).json({ success: false, message: error.message }); } };
exports.updateSettings = async (req, res) => { try {
  const allowed = Object.keys(settingDefaults), supplied = Object.entries(req.body).filter(([key]) => allowed.includes(key));
  if (!supplied.length) return res.status(400).json({ success: false, message: "No valid settings supplied" });
  await Promise.all(supplied.map(([key, value]) => SystemSetting.findOneAndUpdate({ key }, { value, updatedBy: req.user._id }, { upsert: true, new: true, runValidators: true })));
  const rows = await SystemSetting.find().lean(), data = { ...settingDefaults }; rows.forEach((row) => { data[row.key] = row.value; });
  res.json({ success: true, message: "System settings updated", data });
} catch (error) { res.status(500).json({ success: false, message: error.message }); } };

exports.reportSummary = async (req, res) => { try {
  const now = new Date(), from = new Date(now.getFullYear(), now.getMonth(), 1);
  const [labours, activeLabours, sites, attendance, salary, invoices] = await Promise.all([
    Labour.countDocuments({ isDeleted: false }), Labour.countDocuments({ isDeleted: false, status: "ACTIVE" }), Site.countDocuments({ isDeleted: false }),
    Attendance.aggregate([{ $match: { isDeleted: false, attendanceDate: { $gte: from } } }, { $group: { _id: "$status", count: { $sum: 1 } } }]),
    SalarySlip.aggregate([{ $match: { isDeleted: false } }, { $group: { _id: null, net: { $sum: "$netSalary" }, paid: { $sum: "$paidAmount" }, balance: { $sum: "$balanceAmount" } } }]),
    SiteInvoice.aggregate([{ $match: { isDeleted: false, status: { $ne: "CANCELLED" } } }, { $group: { _id: null, billed: { $sum: "$totalAmount" }, received: { $sum: "$paidAmount" }, outstanding: { $sum: "$balanceAmount" } } }])
  ]);
  res.json({ success: true, data: { workforce: { total: labours, active: activeLabours, sites }, attendance: Object.fromEntries(attendance.map((x) => [x._id, x.count])), payroll: salary[0] || { net: 0, paid: 0, balance: 0 }, invoices: invoices[0] || { billed: 0, received: 0, outstanding: 0 } } });
} catch (error) { res.status(500).json({ success: false, message: error.message }); } };

const billingMonths = { MONTHLY: 1, QUARTERLY: 3, HALF_YEARLY: 6, YEARLY: 12, CUSTOM: 1 };
exports.paymentProof = async (req, res) => { try { const subscription = await Subscription.findOne({ _id: req.params.id, isDeleted: false }).select("paymentProofPath paymentProofOriginalName").lean(); if (!subscription?.paymentProofPath) return res.status(404).json({ success: false, message: "Payment proof not found" }); const resolved = path.resolve(subscription.paymentProofPath); if (!resolved.startsWith(path.resolve(proofDirectory) + path.sep) || !fs.existsSync(resolved)) return res.status(404).json({ success: false, message: "Payment proof file not found" }); res.setHeader("Content-Disposition", `inline; filename*=UTF-8''${encodeURIComponent(subscription.paymentProofOriginalName || "payment-proof")}`); res.sendFile(resolved); } catch (error) { res.status(500).json({ success: false, message: error.message }); } };
exports.verifySubscriptionPayment = async (req, res) => { try { const decision = String(req.body.decision || "").toUpperCase(); if (!["APPROVE", "REJECT"].includes(decision)) return res.status(400).json({ success: false, message: "Decision must be APPROVE or REJECT" }); const subscription = await Subscription.findOne({ _id: req.params.id, isDeleted: false }); if (!subscription) return res.status(404).json({ success: false, message: "Subscription not found" }); if (subscription.verificationStatus !== "PENDING") return res.status(409).json({ success: false, message: "Only pending payments can be verified" }); if (decision === "REJECT") { const reason = String(req.body.reason || "").trim(); if (reason.length < 3) return res.status(400).json({ success: false, message: "Rejection reason is required" }); subscription.verificationStatus = "REJECTED"; subscription.paymentStatus = "FAILED"; subscription.status = "SUSPENDED"; subscription.rejectionReason = reason; } else { const start = new Date(), end = new Date(start); end.setMonth(end.getMonth() + (billingMonths[subscription.billingCycle] || 1)); subscription.startDate = start; subscription.endDate = end; subscription.verificationStatus = "APPROVED"; subscription.paymentStatus = "PAID"; subscription.status = "ACTIVE"; subscription.rejectionReason = ""; } subscription.verifiedAt = new Date(); subscription.verifiedBy = req.user._id; subscription.updatedBy = req.user._id; await subscription.save(); res.json({ success: true, message: decision === "APPROVE" ? "Payment verified and subscription activated" : "Payment rejected", data: subscription }); } catch (error) { res.status(400).json({ success: false, message: error.message }); } };


