const bcrypt=require("bcryptjs"),mongoose=require("mongoose");
const Company=require("../models/Company"),User=require("../models/User"),Labour=require("../models/Labour"),Site=require("../models/Site"),Attendance=require("../models/Attendance"),LabourPayment=require("../models/LabourPayment"),SalarySlip=require("../models/SalarySlip"),SiteInvoice=require("../models/SiteInvoice");
const Skill=require("../models/Skill"),LabourSite=require("../models/LabourSite"),PayrollSetting=require("../models/PayrollSetting"),SalaryPayment=require("../models/SalaryPayment");
const generateEmployeeCode=require("../utils/generateEmployeeCode");
const cleanUser="-password -resetOtp -resetOtpExpire -isResetOtpVerified";
const activeCompany={isDeleted:{$ne:true}};
const pages=q=>{const page=Math.max(1,+q.page||1),limit=Math.min(100,Math.max(1,+q.limit||20));return{page,limit,skip:(page-1)*limit}};
const result=(data,total,p,l)=>({success:true,data,pagination:{page:p,limit:l,total,pages:Math.ceil(total/l)}});
const valid=id=>mongoose.Types.ObjectId.isValid(id);
const search=value=>new RegExp(String(value||"").replace(/[|\\{}()[\]^$+*?.-]/g,"\\$&"),"i");
const nextCode=async()=>{const x=await Company.findOne({companyCode:/^COMP-\d+$/}).sort({companyCode:-1}).lean();return"COMP-"+String(+(x?.companyCode?.split("-")[1]||0)+1).padStart(4,"0")};

exports.dashboard = async (req, res) => { try {
  const now = new Date(), monthStart = new Date(now.getFullYear(), now.getMonth(), 1), trendStart = new Date(now.getFullYear(), now.getMonth() - 5, 1);
  const [total, active, blocked, users, labours, sites, attendance, payments, invoices, attendanceBreakdown, companyTrend, labourTrend, paymentTrend, recentCompanies] = await Promise.all([
    Company.countDocuments(activeCompany), Company.countDocuments({ ...activeCompany, status: "ACTIVE" }), Company.countDocuments({ ...activeCompany, status: "BLOCKED" }),
    User.countDocuments({ role: { $ne: "SUPER_ADMIN" }, isDeleted: false }), Labour.countDocuments({ isDeleted: false }), Site.countDocuments({ isDeleted: false }),
    Attendance.countDocuments({ isDeleted: false, attendanceDate: { $gte: monthStart } }),
    LabourPayment.aggregate([{ $match: { isDeleted: false, paymentDate: { $gte: monthStart } } }, { $group: { _id: null, count: { $sum: 1 }, amount: { $sum: "$amount" } } }]),
    SiteInvoice.aggregate([{ $match: { isDeleted: false, issueDate: { $gte: monthStart }, status: { $ne: "CANCELLED" } } }, { $group: { _id: null, billed: { $sum: "$totalAmount" }, received: { $sum: "$paidAmount" }, outstanding: { $sum: "$balanceAmount" } } }]),
    Attendance.aggregate([{ $match: { isDeleted: false, attendanceDate: { $gte: monthStart } } }, { $group: { _id: "$status", count: { $sum: 1 } } }]),
    Company.aggregate([{ $match: { ...activeCompany, createdAt: { $gte: trendStart } } }, { $group: { _id: { year: { $year: "$createdAt" }, month: { $month: "$createdAt" } }, count: { $sum: 1 } } }]),
    Labour.aggregate([{ $match: { isDeleted: false, createdAt: { $gte: trendStart } } }, { $group: { _id: { year: { $year: "$createdAt" }, month: { $month: "$createdAt" } }, count: { $sum: 1 } } }]),
    LabourPayment.aggregate([{ $match: { isDeleted: false, paymentDate: { $gte: trendStart } } }, { $group: { _id: { year: { $year: "$paymentDate" }, month: { $month: "$paymentDate" } }, amount: { $sum: "$amount" } } }]),
    Company.find(activeCompany).select("companyName companyCode status createdAt").sort({ createdAt: -1 }).limit(5).lean()
  ]);
  const findMonth = (rows, year, month, field) => rows.find((row) => row._id.year === year && row._id.month === month)?.[field] || 0;
  const trends = Array.from({ length: 6 }, (_, index) => { const date = new Date(now.getFullYear(), now.getMonth() - 5 + index, 1); return { label: date.toLocaleString("en", { month: "short" }), year: date.getFullYear(), companies: findMonth(companyTrend, date.getFullYear(), date.getMonth() + 1, "count"), labours: findMonth(labourTrend, date.getFullYear(), date.getMonth() + 1, "count"), payments: findMonth(paymentTrend, date.getFullYear(), date.getMonth() + 1, "amount") }; });
  res.json({ success: true, data: { companies: { total, active, blocked, inactive: total - active - blocked }, users, labours, sites, currentMonth: { attendance, attendanceBreakdown: Object.fromEntries(attendanceBreakdown.map((row) => [row._id, row.count])), payments: payments[0] || { count: 0, amount: 0 }, invoices: invoices[0] || { billed: 0, received: 0, outstanding: 0 } }, trends, recentCompanies } });
} catch (error) { res.status(500).json({ success: false, message: error.message }); } };
exports.listCompanies=async(req,res)=>{try{const{page,limit,skip}=pages(req.query),f={...activeCompany};if(req.query.status)f.status=req.query.status;if(req.query.search){const r=search(req.query.search);f.$or=[{companyName:r},{companyCode:r},{ownerName:r},{email:r},{mobile:r}]}const[data,total]=await Promise.all([Company.find(f).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Company.countDocuments(f)]);res.json(result(data,total,page,limit))}catch(e){res.status(500).json({success:false,message:e.message})}};
const stats=async id=>{const oid=new mongoose.Types.ObjectId(id),[users,labours,sites,attendance,salary,invoices]=await Promise.all([User.countDocuments({companyId:id,isDeleted:false}),Labour.countDocuments({companyId:id,isDeleted:false}),Site.countDocuments({companyId:id,isDeleted:false}),Attendance.countDocuments({companyId:id,isDeleted:false}),SalarySlip.aggregate([{$match:{companyId:oid,isDeleted:false}},{$group:{_id:null,net:{$sum:"$netSalary"},paid:{$sum:"$paidAmount"},balance:{$sum:"$balanceAmount"}}}]),SiteInvoice.aggregate([{$match:{companyId:oid,isDeleted:false,status:{$ne:"CANCELLED"}}},{$group:{_id:null,billed:{$sum:"$totalAmount"},received:{$sum:"$paidAmount"},balance:{$sum:"$balanceAmount"}}}])]);return{users,labours,sites,attendance,salary:salary[0]||{},invoices:invoices[0]||{}}};
exports.getCompany=async(req,res)=>{try{if(!valid(req.params.id))return res.status(400).json({success:false,message:"Invalid company id"});const company=await Company.findOne({_id:req.params.id,...activeCompany}).lean();if(!company)return res.status(404).json({success:false,message:"Company not found"});const[contractor,usage]=await Promise.all([User.findOne({companyId:company._id,role:"CONTRACTOR",isDeleted:false}).select(cleanUser).lean(),stats(req.params.id)]);res.json({success:true,data:{...company,contractor,stats:usage}})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.createCompany=async(req,res)=>{let company;try{const{companyName,ownerName,email,mobile,password,address,gstNumber}=req.body;if(!companyName||!ownerName||!email||!mobile||!password||!address?.street||!address?.city||!address?.state||!address?.pincode)return res.status(400).json({success:false,message:"Complete company, owner, contact, password and address are required"});if(password.length<8)return res.status(400).json({success:false,message:"Password must be at least 8 characters"});if(await User.exists({$or:[{email},{mobile}],isDeleted:false}))return res.status(409).json({success:false,message:"Email or mobile already exists"});company=await Company.create({companyCode:await nextCode(),companyName,ownerName,email,mobile,address:{...address,country:address.country||"India"},gstNumber,status:"ACTIVE",createdBy:req.user._id});const user=await User.create({companyId:company._id,employeeCode:await generateEmployeeCode("CONTRACTOR"),name:ownerName,email,mobile,password:await bcrypt.hash(password,10),role:"CONTRACTOR",status:"ACTIVE",isActive:true,createdBy:req.user._id});const safe=user.toObject();delete safe.password;res.status(201).json({success:true,message:"Company and contractor created",data:{company,contractor:safe}})}catch(e){if(company)await Company.deleteOne({_id:company._id});res.status(e.code===11000?409:500).json({success:false,message:e.code===11000?"Company code, email or mobile exists":e.message})}};
exports.updateCompany=async(req,res)=>{try{const allowed=["companyName","ownerName","email","mobile","address","gstNumber"],set={};allowed.forEach(k=>{if(req.body[k]!==undefined)set[k]=req.body[k]});const data=await Company.findOneAndUpdate({_id:req.params.id,...activeCompany},{$set:set},{new:true,runValidators:true});if(!data)return res.status(404).json({success:false,message:"Company not found"});res.json({success:true,message:"Company updated",data})}catch(e){res.status(e.code===11000?409:500).json({success:false,message:e.message})}};
exports.companyStatus=async(req,res)=>{try{const status=req.body.status;if(!["ACTIVE","INACTIVE","BLOCKED"].includes(status))return res.status(400).json({success:false,message:"Invalid status"});const data=await Company.findOneAndUpdate({_id:req.params.id,...activeCompany},{status},{new:true});if(!data)return res.status(404).json({success:false,message:"Company not found"});if(status!=="ACTIVE")await User.updateMany({companyId:data._id,isDeleted:false},{isActive:false,status});else await User.updateMany({companyId:data._id,role:"CONTRACTOR",isDeleted:false},{isActive:true,status:"ACTIVE"});res.json({success:true,message:"Company status updated",data})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.deleteCompany=async(req,res)=>{try{const data=await Company.findOneAndUpdate({_id:req.params.id,...activeCompany},{isDeleted:true,status:"INACTIVE",deletedAt:new Date(),deletedBy:req.user._id},{new:true});if(!data)return res.status(404).json({success:false,message:"Company not found"});await User.updateMany({companyId:data._id,isDeleted:false},{isDeleted:true,isActive:false,status:"INACTIVE"});res.json({success:true,message:"Company and user access deleted"})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.listUsers=async(req,res)=>{try{const{page,limit,skip}=pages(req.query),f={isDeleted:false,role:{$ne:"SUPER_ADMIN"}};["companyId","role","status"].forEach(k=>{if(req.query[k])f[k]=req.query[k]});if(req.query.search){const r=search(req.query.search);f.$or=[{name:r},{email:r},{mobile:r},{employeeCode:r}]}const[data,total]=await Promise.all([User.find(f).select(cleanUser).populate("companyId","companyCode companyName status").sort({createdAt:-1}).skip(skip).limit(limit).lean(),User.countDocuments(f)]);res.json(result(data,total,page,limit))}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.getUser=async(req,res)=>{try{const data=await User.findOne({_id:req.params.id,role:{$ne:"SUPER_ADMIN"},isDeleted:false}).select(cleanUser).populate("companyId","companyCode companyName status");if(!data)return res.status(404).json({success:false,message:"User not found"});res.json({success:true,data})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.updateUser=async(req,res)=>{try{const set={};["name","email","mobile"].forEach(k=>{if(req.body[k]!==undefined)set[k]=req.body[k]});if(req.body.password){if(req.body.password.length<8)return res.status(400).json({success:false,message:"Password must be at least 8 characters"});set.password=await bcrypt.hash(req.body.password,10)}const data=await User.findOneAndUpdate({_id:req.params.id,role:{$ne:"SUPER_ADMIN"},isDeleted:false},{$set:set},{new:true,runValidators:true}).select(cleanUser);if(!data)return res.status(404).json({success:false,message:"User not found"});res.json({success:true,message:"User updated",data})}catch(e){res.status(e.code===11000?409:500).json({success:false,message:e.message})}};
exports.userStatus=async(req,res)=>{try{const status=req.body.status;if(!["ACTIVE","INACTIVE","BLOCKED"].includes(status))return res.status(400).json({success:false,message:"Invalid status"});const data=await User.findOne({_id:req.params.id,role:{$ne:"SUPER_ADMIN"},isDeleted:false}).populate("companyId","status");if(!data)return res.status(404).json({success:false,message:"User not found"});if(status==="ACTIVE"&&data.companyId?.status!=="ACTIVE")return res.status(409).json({success:false,message:"Activate company first"});data.status=status;data.isActive=status==="ACTIVE";await data.save();res.json({success:true,message:"User status updated",data})}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.deleteUser=async(req,res)=>{try{const data=await User.findOneAndUpdate({_id:req.params.id,role:{$ne:"SUPER_ADMIN"},isDeleted:false},{isDeleted:true,isActive:false,status:"INACTIVE"},{new:true});if(!data)return res.status(404).json({success:false,message:"User not found"});res.json({success:true,message:"User deleted"})}catch(e){res.status(500).json({success:false,message:e.message})}};


const resources={
  labours:{model:Labour,date:"createdAt",search:["name","labourCode","mobile"],populate:[["companyId","companyCode companyName status"],["skillId","skillName skillCode"]]},
  sites:{model:Site,date:"createdAt",search:["siteName","siteCode","clientName","location"],populate:[["companyId","companyCode companyName status"]]},
  attendance:{model:Attendance,date:"attendanceDate",search:[],populate:[["companyId","companyCode companyName"],["labourId","name labourCode"],["siteId","siteName siteCode"]]},
  payments:{model:LabourPayment,date:"paymentDate",search:["labourNameSnapshot","labourCodeSnapshot","remarks"],populate:[["companyId","companyCode companyName"],["labourId","name labourCode"]]},
  "salary-slips":{model:SalarySlip,date:"createdAt",search:[],populate:[["companyId","companyCode companyName"],["labourId","name labourCode"],["skillId","skillName skillCode"]]},
  "salary-payments":{model:SalaryPayment,date:"paymentDate",search:["remarks"],populate:[["companyId","companyCode companyName"],["labourId","name labourCode"],["salaryId","month year status"]]},
  invoices:{model:SiteInvoice,date:"issueDate",search:["invoiceNumber","siteName","clientName"],populate:[["companyId","companyCode companyName"],["siteId","siteName siteCode"]]},
  skills:{model:Skill,date:"createdAt",search:["skillName","skillCode"],populate:[["companyId","companyCode companyName"]]},
  "labour-sites":{model:LabourSite,date:"createdAt",search:[],populate:[["companyId","companyCode companyName"],["labourId","name labourCode"],["siteId","siteName siteCode"],["supervisorId","name employeeCode"]]},
  "payroll-settings":{model:PayrollSetting,date:"createdAt",search:[],populate:[["companyId","companyCode companyName"],["contractorId","name employeeCode"]]}
};
exports.platformData=async(req,res)=>{try{
  const config=resources[req.params.resource];
  if(!config)return res.status(404).json({success:false,message:"Unknown resource",supported:Object.keys(resources)});
  const{page,limit,skip}=pages(req.query),f={};
  if(req.query.companyId){if(!valid(req.query.companyId))return res.status(400).json({success:false,message:"Invalid companyId"});f.companyId=req.query.companyId}
  if(config.model.schema.path("isDeleted")&&req.query.includeDeleted!=="true")f.isDeleted=false;
  if(req.query.status&&config.model.schema.path("status"))f.status=req.query.status;
  if(req.query.month&&config.model.schema.path("month"))f.month=Number(req.query.month);
  if(req.query.year&&config.model.schema.path("year"))f.year=Number(req.query.year);
  if(req.query.from||req.query.to){f[config.date]={};if(req.query.from)f[config.date].$gte=new Date(req.query.from);if(req.query.to){const end=new Date(req.query.to);end.setHours(23,59,59,999);f[config.date].$lte=end}}
  if(req.query.search&&config.search.length){const r=search(req.query.search);f.$or=config.search.map(field=>({[field]:r}))}
  let query=config.model.find(f).sort({[config.date]:-1}).skip(skip).limit(limit);
  config.populate.forEach(args=>{query=query.populate(...args)});
  const[data,total]=await Promise.all([query.lean(),config.model.countDocuments(f)]);
  res.json({...result(data,total,page,limit),resource:req.params.resource,filters:f});
}catch(e){res.status(500).json({success:false,message:e.message})}};
exports.platformResources=(req,res)=>res.json({success:true,data:Object.keys(resources)});

