"use client"
import { useMemo, useState } from "react"
import { BarChart, DonutChart, Filters, money, ReportActions, pad, refId, ReportPage, Stat } from "../_components/report-ui"
import { useReportData } from "../_components/use-report-data"
export default function PaymentReportPage(){
 const now=new Date(),[month,setMonth]=useState(`${now.getFullYear()}-${pad(now.getMonth()+1)}`),[siteId,setSiteId]=useState(""),[query,setQuery]=useState(""),[type,setType]=useState("")
 const {payments,sites,labourMap,loading}=useReportData(month)
 const rows=useMemo(()=>payments.filter(p=>{const embedded=typeof p.labourId==="object"?p.labourId:null,l=labourMap.get(refId(p.labourId))||embedded,q=query.trim().toLowerCase();return(!siteId||l?.site?._id===siteId)&&(!type||p.paymentType===type)&&(!q||[l?.name,l?.labourCode,l?.mobile,p.remarks].some(v=>(v||"").toLowerCase().includes(q)))}),[payments,labourMap,query,siteId,type])
 const sum=(t?:string)=>rows.filter(p=>!t||p.paymentType===t).reduce((s,p)=>s+Number(p.amount||0),0)
 const types=["SALARY","ADVANCE","BONUS","INCENTIVE","DEDUCTION"],colors=["#4f46e5","#f59e0b","#10b981","#06b6d4","#ef4444"]
 return <ReportPage title="Payment Report" description="Salary, advance, bonus, incentive aur deduction transactions ka monthly record."><Filters month={month} setMonth={setMonth} siteId={siteId} setSiteId={setSiteId} sites={sites}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search labour or remark..." className="h-10 min-w-52 flex-1 rounded-md border border-slate-300 px-3 text-sm"/><select value={type} onChange={e=>setType(e.target.value)} className="h-10 rounded-md border border-slate-300 bg-white px-3 text-sm"><option value="">All Payment Types</option>{types.map(t=><option key={t}>{t}</option>)}</select><ReportActions title="Payment Report" fileName={"Payment_Report_"+month} tableId="payment-report-table" /></Filters>
 <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Total Transactions" value={money.format(sum())}/><Stat label="Salary" value={money.format(sum("SALARY"))} tone="text-indigo-700"/><Stat label="Advance" value={money.format(sum("ADVANCE"))} tone="text-amber-700"/><Stat label="Bonus & Incentive" value={money.format(sum("BONUS")+sum("INCENTIVE"))} tone="text-emerald-700"/><Stat label="Deductions" value={money.format(sum("DEDUCTION"))} tone="text-red-600"/></section>
 <section className="mt-5 grid gap-5 xl:grid-cols-2"><DonutChart title="Payment Type Mix" format={money.format} items={types.map((t,i)=>({label:t,value:sum(t),color:colors[i]}))}/><BarChart title="Payment Modes" format={money.format} items={["CASH","BANK","UPI"].map((m,i)=>({label:m,value:rows.filter(p=>p.paymentMode===m).reduce((s,p)=>s+Number(p.amount||0),0),color:["bg-emerald-500","bg-indigo-500","bg-violet-500"][i]}))}/></section>
 <section className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table id="payment-report-table" className="w-full min-w-[900px] border-collapse text-left"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{["Date","Labour","Site","Type","Mode","Amount","Remarks"].map(h=><th key={h} className="border-b border-r border-slate-200 px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(p=>{const embedded=typeof p.labourId==="object"?p.labourId:null,l=labourMap.get(refId(p.labourId))||embedded;return <tr key={p._id} className="hover:bg-slate-50"><td className="border-b px-4 py-3 text-xs">{new Date(p.paymentDate).toLocaleDateString("en-IN")}</td><td className="border-b px-4"><strong className="block text-xs">{l?.name||"Unknown Labour"}</strong><span className="text-[9px] text-slate-400">{l?.labourCode||"-"}</span></td><td className="border-b px-4 text-xs">{l?.site?.siteName||"No site"}</td><td className="border-b px-4 text-xs font-semibold">{p.paymentType}</td><td className="border-b px-4 text-xs">{p.paymentMode}</td><td className="border-b px-4 text-xs font-bold">{money.format(p.amount)}</td><td className="border-b px-4 text-xs text-slate-500">{p.remarks||"-"}</td></tr>})}</tbody></table></div>{loading&&<p className="p-8 text-center text-sm text-slate-400">Loading report...</p>}{!loading&&!rows.length&&<p className="p-8 text-center text-sm text-slate-400">No payment records found.</p>}</section>
 </ReportPage>
}

