"use client"

import { FormEvent, useCallback, useEffect, useState } from "react"
import PageLoader from "@/app/components/page-loader"
import { useToast } from "@/app/components/toast-provider"
import { Pagination, Status, superAdminApi } from "@/lib/super-admin"

type User = { _id: string; employeeCode: string; name: string; email: string; mobile: string; role: string; status: Status; companyId?: { _id: string; companyCode: string; companyName: string; status: Status } }
const badge: Record<Status, string> = { ACTIVE: "bg-emerald-50 text-emerald-700", INACTIVE: "bg-amber-50 text-amber-700", BLOCKED: "bg-red-50 text-red-700" }

export default function UsersPage() {
  const { showToast } = useToast(), [rows, setRows] = useState<User[]>([]), [pagination, setPagination] = useState<Pagination | null>(null)
  const [search, setSearch] = useState(""), [role, setRole] = useState(""), [status, setStatus] = useState(""), [page, setPage] = useState(1), [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState<User | null>(null), [form, setForm] = useState({ name: "", email: "", mobile: "", password: "" }), [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const q = new URLSearchParams({ page: String(page), limit: "20" }); if (search) q.set("search", search); if (role) q.set("role", role); if (status) q.set("status", status); const r = await superAdminApi<User[]>(`/users?${q}`); setRows(r.data); setPagination(r.pagination || null) } catch (e) { showToast(e instanceof Error ? e.message : "Users could not load", "error") } finally { setLoading(false) } }, [page, role, search, status, showToast])
  useEffect(() => { const id = setTimeout(() => void load(), 250); return () => clearTimeout(id) }, [load])
  const edit = (user: User) => { setEditing(user); setForm({ name: user.name, email: user.email, mobile: user.mobile, password: "" }) }
  const submit = async (e: FormEvent) => { e.preventDefault(); if (!editing) return; setSaving(true); try { await superAdminApi(`/users/${editing._id}`, { method: "PUT", body: JSON.stringify({ name: form.name, email: form.email, mobile: form.mobile, ...(form.password ? { password: form.password } : {}) }) }); showToast("User updated", "success"); setEditing(null); load() } catch (e) { showToast(e instanceof Error ? e.message : "Update failed", "error") } finally { setSaving(false) } }
  const changeStatus = async (user: User, next: Status) => { try { await superAdminApi(`/users/${user._id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); showToast("User status updated", "success"); load() } catch (e) { showToast(e instanceof Error ? e.message : "Status failed", "error") } }
  const remove = async (user: User) => { if (!confirm(`Delete ${user.name}?`)) return; try { await superAdminApi(`/users/${user._id}`, { method: "DELETE" }); showToast("User deleted", "success"); load() } catch (e) { showToast(e instanceof Error ? e.message : "Delete failed", "error") } }
  return <div><div><p className="text-sm font-semibold text-violet-600">Access Management</p><h1 className="mt-1 text-3xl font-black text-slate-950">Platform Users</h1><p className="mt-1 text-sm text-slate-500">Manage every Contractor, Supervisor and Accountant account.</p></div>
    <div className="mt-6 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_180px_160px]"><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }} placeholder="Search user, employee code, email or mobile" className="h-10 rounded-lg border px-3 text-sm" /><select value={role} onChange={(e) => { setRole(e.target.value); setPage(1) }} className="rounded-lg border px-3 text-sm"><option value="">All roles</option><option>CONTRACTOR</option><option>SUPERVISOR</option><option>ACCOUNTANT</option></select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }} className="rounded-lg border px-3 text-sm"><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option><option>BLOCKED</option></select></div>
    <div className="mt-4 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">{loading ? <PageLoader label="Loading users" /> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{["User", "Company", "Role", "Contact", "Status", "Actions"].map((h) => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((u) => <tr key={u._id} className="hover:bg-slate-50"><td className="px-4 py-4"><strong>{u.name}</strong><small className="block text-slate-500">{u.employeeCode}</small></td><td className="px-4 py-4"><span>{u.companyId?.companyName || "-"}</span><small className="block text-slate-500">{u.companyId?.companyCode}</small></td><td className="px-4 py-4 text-xs font-bold text-indigo-700">{u.role}</td><td className="px-4 py-4"><span className="block">{u.email}</span><small>{u.mobile}</small></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${badge[u.status]}`}>{u.status}</span></td><td className="px-4 py-4"><div className="flex items-center gap-2 whitespace-nowrap"><button onClick={() => edit(u)} title="Edit user" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-indigo-200 bg-indigo-50 px-3 text-xs font-bold text-indigo-700 transition hover:-translate-y-0.5 hover:bg-indigo-600 hover:text-white">✎ <span>Edit</span></button><label className="relative"><span className="sr-only">Change user status</span><select value={u.status} onChange={(e) => changeStatus(u, e.target.value as Status)} className="h-9 cursor-pointer appearance-none rounded-lg border border-slate-200 bg-white pl-3 pr-7 text-[10px] font-bold text-slate-700 shadow-sm outline-none transition hover:border-slate-400 focus:border-violet-500"><option>ACTIVE</option><option>INACTIVE</option><option>BLOCKED</option></select><span className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-slate-400">▼</span></label><button onClick={() => remove(u)} title="Delete user" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-red-200 bg-red-50 px-3 text-xs font-bold text-red-600 transition hover:-translate-y-0.5 hover:bg-red-600 hover:text-white">⌫ <span>Delete</span></button></div></td></tr>)}</tbody></table>{!rows.length && <p className="p-10 text-center text-slate-500">No users found.</p>}</div>}</div>
    {pagination && <div className="mt-4 flex justify-between text-sm text-slate-500"><span>{pagination.total} users</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1 disabled:opacity-40">Previous</button><span>{page} / {pagination.pages || 1}</span><button disabled={page >= pagination.pages} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div>}
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Edit User</h2><p className="text-sm text-slate-500">{editing.role} â€¢ {editing.companyId?.companyName}</p></div><button type="button" onClick={() => setEditing(null)} className="text-2xl">Ã—</button></div><div className="mt-5 space-y-4">{[["Name", "name", "text"], ["Email", "email", "email"], ["Mobile", "mobile", "text"], ["New Password (optional)", "password", "password"]].map(([label, key, type]) => <label key={key} className="block text-xs font-semibold text-slate-600">{label}<input required={key !== "password"} minLength={key === "password" ? 8 : undefined} type={type} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 h-11 w-full rounded-lg border px-3 text-sm" /></label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)} className="rounded-lg border px-4 py-2">Cancel</button><button disabled={saving} className="rounded-lg bg-violet-600 px-5 py-2 font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Save User"}</button></div></form></div>}
  </div>
}


