"use client"
import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import Navbar from "@/app/components/navbar"
import Sidebar from "@/app/components/sidebar"
import PageLoader from "@/app/components/page-loader"
import { apiUrl } from "@/lib/api"
import { useToast } from "@/app/components/toast-provider"
type Item={description:string;unit:string;quantity:number;rate:number;amount:number;remark?:string}
type Quotation={_id:string;quotationNumber:string;siteName:string;siteCode:string;clientName:string;clientAddress?:string;subject:string;issueDate:string;validUntil:string;items:Item[];subtotal:number;discountPercent:number;discountAmount:number;taxableAmount:number;gstPercent:number;gstAmount:number;totalAmount:number;status:string;notes?:string;terms?:string}
type Api<T>={success:boolean;data?:T;message?:string}
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}),date=(v:string)=>new Date(v).toLocaleDateString("en-IN",{dateStyle:"medium"})
const colors:Record<string,string>={DRAFT:"bg-slate-100 text-slate-700",SENT:"bg-blue-100 text-blue-700",ACCEPTED:"bg-emerald-100 text-emerald-700",REJECTED:"bg-red-100 text-red-700",EXPIRED:"bg-amber-100 text-amber-700"}
export default function Quotations(){
 const {showToast}=useToast(),[data,setData]=useState<Quotation[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState<Quotation|null>(null)
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(apiUrl("/quotations"),{credentials:"include"}),j:Api<Quotation[]>=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Could not load quotations");setData(j.data||[])}catch(e){showToast(e instanceof Error?e.message:"Could not load quotations","error")}finally{setLoading(false)}},[showToast])
 useEffect(()=>{load()},[load])
 const rows=useMemo(()=>data.filter(q=>(!status||q.status===status)&&[q.quotationNumber,q.siteName,q.clientName,q.subject].join(" ").toLowerCase().includes(search.toLowerCase())),[data,search,status])
 async function setQuotationStatus(q:Quotation,value:string){const r=await fetch(apiUrl(`/quotations/${q._id}/status`),{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:value})}),j:Api<Quotation>=await r.json();if(!r.ok||!j.success)return showToast(j.message||"Status could not be updated","error");setData(data.map(x=>x._id===q._id?j.data!:x));if(selected?._id===q._id)setSelected(j.data!);showToast("Quotation status updated","success")}
 async function downloadPdf(q:Quotation){const element=document.getElementById(`quotation-document-${q._id}`);if(!element)return showToast("Quotation preview not found","error");const nodes=[element,...Array.from(element.querySelectorAll<HTMLElement>("*"))];const originalStyles=nodes.map(node=>node.getAttribute("style"));try{element.style.width="100%";element.style.maxWidth="none";element.style.overflow="visible";element.style.backgroundColor="#ffffff";element.style.color="#111111";nodes.forEach(node=>{node.style.color="#111111";node.style.borderColor="#111111";node.style.boxShadow="none";node.style.textShadow="none"});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));const rect=element.getBoundingClientRect();if(rect.width<100||rect.height<100)throw new Error("Quotation content could not be rendered");const pdfModule=await import("html2pdf.js");const html2pdf=pdfModule.default;if(typeof html2pdf!=="function")throw new Error("PDF library could not be loaded");await html2pdf().set({margin:[8,8,8,8],filename:`Quotation-${q.quotationNumber}.pdf`,image:{type:"jpeg",quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:"#ffffff",logging:false,scrollX:0,scrollY:-window.scrollY},jsPDF:{unit:"mm",format:"a4",orientation:"portrait"}}).from(element).save();showToast("Quotation PDF downloaded","success")}catch(e){console.error("Quotation PDF export failed",e);showToast(e instanceof Error?`PDF error: ${e.message}`:"PDF export failed","error")}finally{nodes.forEach((node,index)=>{const style=originalStyles[index];if(style===null)node.removeAttribute("style");else node.setAttribute("style",style)})}}
 function downloadWord(q:Quotation){const element=document.getElementById(`quotation-document-${q._id}`);if(!element)return showToast("Quotation preview not found","error");const styles=`<style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#111;font-size:12pt}.quotation-sheet{padding:0!important}table{width:100%;border-collapse:collapse}th,td{border:1px solid #111;padding:8px}th{text-align:center}.to-block{line-height:1.45}.quotation-title{text-align:center;text-decoration:underline;margin:26px 0 12px}.signature{margin-top:70px;text-align:right}.summary{width:310px;margin:18px 0 0 auto}.summary td{border:0;padding:3px}.notes{margin-top:28px;white-space:pre-wrap}</style>`;const blob=new Blob([`<!DOCTYPE html><html><head><meta charset="utf-8">${styles}</head><body>${element.outerHTML}</body></html>`],{type:"application/msword"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`Quotation-${q.quotationNumber}.doc`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);showToast("Quotation Word file downloaded","success")}
 return <div className="flex min-h-screen bg-slate-50"><Sidebar/><div className="min-w-0 flex-1"><Navbar/><main className="p-6">
  <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold text-indigo-600">Contractor workspace</p><h1 className="mt-1 text-2xl font-bold">Quotations</h1><p className="mt-1 text-sm text-slate-500">Create and track price proposals sent for site work.</p></div><Link href="/pages/contractorpages/quotations/generate" className="rounded-md bg-indigo-700 px-5 py-2.5 text-sm font-bold text-white">+ Create Quotation</Link></header>
  <section className="mb-4 grid gap-3 rounded-xl border bg-white p-4 shadow-sm sm:grid-cols-[1fr_200px]"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotation, site or client..." className="h-11 rounded-md border px-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-md border px-3 text-sm"><option value="">All statuses</option>{["DRAFT","SENT","ACCEPTED","REJECTED","EXPIRED"].map(s=><option key={s}>{s}</option>)}</select></section>
  {loading?<PageLoader label="Loading quotations"/>:<section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Quotation</th><th className="px-5 py-4">Site / Client</th><th className="px-5 py-4">Validity</th><th className="px-5 py-4 text-right">Amount</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody className="divide-y">{rows.map(q=><tr key={q._id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-indigo-700">{q.quotationNumber}</p><p className="mt-1 max-w-64 truncate text-xs text-slate-500">{q.subject}</p></td><td className="px-5 py-4"><p className="font-semibold">{q.siteName}</p><p className="text-xs text-slate-500">{q.clientName}</p></td><td className="px-5 py-4 text-xs"><p>{date(q.issueDate)}</p><p className="mt-1 text-slate-500">to {date(q.validUntil)}</p></td><td className="px-5 py-4 text-right font-bold">{money.format(q.totalAmount)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${colors[q.status]||colors.DRAFT}`}>{q.status}</span></td><td className="px-5 py-4 text-right"><button onClick={()=>setSelected(q)} className="rounded-md border px-3 py-2 text-xs font-bold text-indigo-700">View / Print</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-14 text-center text-sm text-slate-500">No quotations found. Create your first site work quotation.</div>}</section>}
  {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4 print:static print:bg-white print:p-0"><div className="mx-auto max-w-4xl rounded-xl bg-white shadow-2xl print:max-w-none print:shadow-none"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4 print:hidden"><select value={selected.status} onChange={e=>setQuotationStatus(selected,e.target.value)} className="rounded-md border px-3 py-2 text-sm">{["DRAFT","SENT","ACCEPTED","REJECTED","EXPIRED"].map(s=><option key={s}>{s}</option>)}</select><div className="flex flex-wrap gap-2"><button onClick={()=>downloadPdf(selected)} className="rounded-md bg-indigo-700 px-4 py-2 text-sm font-bold text-white">Download PDF</button><button onClick={()=>downloadWord(selected)} className="rounded-md border border-indigo-700 px-4 py-2 text-sm font-bold text-indigo-700">Download Word</button><button onClick={()=>window.print()} className="rounded-md border px-4 py-2 text-sm font-semibold">Print</button><button onClick={()=>setSelected(null)} className="rounded-md border px-4 py-2 text-sm">Close</button></div></div>
   <article id={`quotation-document-${selected._id}`} className="quotation-sheet min-h-[1050px] bg-white p-12 font-sans text-[14px] leading-relaxed text-slate-950"><div className="mb-6 flex justify-between text-xs"><b>No.: {selected.quotationNumber}</b><div className="text-right"><p><b>Date:</b> {date(selected.issueDate)}</p><p><b>Valid until:</b> {date(selected.validUntil)}</p></div></div><div className="to-block"><p>To,</p><p className="mt-5 text-base font-bold uppercase">{selected.clientName}</p><p className="font-semibold">{selected.siteName} {selected.siteCode&&`(${selected.siteCode})`}</p>{selected.clientAddress&&<p className="max-w-xl">{selected.clientAddress}</p>}</div><p className="mt-6"><b>SUBJECT :- </b>{selected.subject}</p><h1 className="quotation-title my-7 text-center text-3xl font-bold underline underline-offset-4">Quotation</h1>
   <table className="w-full border-collapse text-sm"><thead><tr><th className="w-14 border border-slate-900 p-2 text-center">S.no.</th><th className="border border-slate-900 p-2 text-center">Particular</th><th className="w-36 border border-slate-900 p-2 text-center">Kg/Nos./Monthly</th><th className="w-28 border border-slate-900 p-2 text-center">Rate</th><th className="w-32 border border-slate-900 p-2 text-center">Amount</th></tr></thead><tbody>{selected.items.map((i,n)=><tr key={n}><td className="border border-slate-900 p-2 text-center">{n+1}</td><td className="border border-slate-900 p-2 font-semibold">{i.description}</td><td className="border border-slate-900 p-2 text-center">{i.quantity} {i.unit}</td><td className="border border-slate-900 p-2 text-right font-semibold">₹{i.rate.toLocaleString("en-IN")}/-</td><td className="border border-slate-900 p-2 text-right font-semibold">{money.format(i.amount)}</td></tr>)}</tbody></table>
   <div className="summary ml-auto mt-5 w-full max-w-80 text-sm"><div className="flex items-center justify-between border-b border-slate-300 px-3 py-2"><span>Subtotal</span><b>{money.format(selected.subtotal)}</b></div>{selected.discountAmount>0&&<div className="flex items-center justify-between border-b border-slate-300 px-3 py-2"><span>Discount ({selected.discountPercent}%)</span><b>- {money.format(selected.discountAmount)}</b></div>}<div className="flex items-center justify-between border-b border-slate-300 px-3 py-2"><span>GST ({selected.gstPercent}%)</span><b>{money.format(selected.gstAmount)}</b></div><div className="flex items-center justify-between border-t-2 border-slate-900 px-3 py-3 text-base"><b>Grand Total</b><b>{money.format(selected.totalAmount)}</b></div></div>
   {(selected.notes||selected.terms)&&<div className="notes mt-8 text-sm"><b>Note :-</b>{selected.notes&&<p className="mt-2 whitespace-pre-wrap">{selected.notes}</p>}{selected.terms&&<p className="mt-1 whitespace-pre-wrap">{selected.terms}</p>}</div>}<div className="signature mt-20 text-right"><p className="font-bold">FOR CONTRACTOR</p><p className="mt-14 font-semibold">Authorized Signature</p></div></article>
  </div></div>}
 </main></div></div>
}
