"use client"
import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import Navbar from "@/app/components/navbar"
import Sidebar from "@/app/components/sidebar"
import PageLoader from "@/app/components/page-loader"
import { apiUrl } from "@/lib/api"
import { useToast } from "@/app/components/toast-provider"
type Item={description:string;unit:string;quantity:number;rate:number;amount:number}
type Quotation={_id:string;quotationNumber:string;siteName:string;siteCode:string;clientName:string;subject:string;issueDate:string;validUntil:string;items:Item[];subtotal:number;discountPercent:number;discountAmount:number;taxableAmount:number;gstPercent:number;gstAmount:number;totalAmount:number;status:string;notes?:string;terms?:string}
type Api<T>={success:boolean;data?:T;message?:string}
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}),date=(v:string)=>new Date(v).toLocaleDateString("en-IN",{dateStyle:"medium"})
const colors:Record<string,string>={DRAFT:"bg-slate-100 text-slate-700",SENT:"bg-blue-100 text-blue-700",ACCEPTED:"bg-emerald-100 text-emerald-700",REJECTED:"bg-red-100 text-red-700",EXPIRED:"bg-amber-100 text-amber-700"}
export default function Quotations(){
 const {showToast}=useToast(),[data,setData]=useState<Quotation[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState<Quotation|null>(null)
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(apiUrl("/quotations"),{credentials:"include"}),j:Api<Quotation[]>=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Could not load quotations");setData(j.data||[])}catch(e){showToast(e instanceof Error?e.message:"Could not load quotations","error")}finally{setLoading(false)}},[showToast])
 useEffect(()=>{load()},[load])
 const rows=useMemo(()=>data.filter(q=>(!status||q.status===status)&&[q.quotationNumber,q.siteName,q.clientName,q.subject].join(" ").toLowerCase().includes(search.toLowerCase())),[data,search,status])
 async function setQuotationStatus(q:Quotation,value:string){const r=await fetch(apiUrl(`/quotations/${q._id}/status`),{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:value})}),j:Api<Quotation>=await r.json();if(!r.ok||!j.success)return showToast(j.message||"Status could not be updated","error");setData(data.map(x=>x._id===q._id?j.data!:x));if(selected?._id===q._id)setSelected(j.data!);showToast("Quotation status updated","success")}
 return <div className="flex min-h-screen bg-slate-50"><Sidebar/><div className="min-w-0 flex-1"><Navbar/><main className="p-6">
  <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold text-indigo-600">Contractor workspace</p><h1 className="mt-1 text-2xl font-bold">Quotations</h1><p className="mt-1 text-sm text-slate-500">Create and track price proposals sent for site work.</p></div><Link href="/pages/contractorpages/quotations/generate" className="rounded-md bg-indigo-700 px-5 py-2.5 text-sm font-bold text-white">+ Create Quotation</Link></header>
  <section className="mb-4 grid gap-3 rounded-xl border bg-white p-4 shadow-sm sm:grid-cols-[1fr_200px]"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotation, site or client..." className="h-11 rounded-md border px-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-md border px-3 text-sm"><option value="">All statuses</option>{["DRAFT","SENT","ACCEPTED","REJECTED","EXPIRED"].map(s=><option key={s}>{s}</option>)}</select></section>
  {loading?<PageLoader label="Loading quotations"/>:<section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Quotation</th><th className="px-5 py-4">Site / Client</th><th className="px-5 py-4">Validity</th><th className="px-5 py-4 text-right">Amount</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody className="divide-y">{rows.map(q=><tr key={q._id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-indigo-700">{q.quotationNumber}</p><p className="mt-1 max-w-64 truncate text-xs text-slate-500">{q.subject}</p></td><td className="px-5 py-4"><p className="font-semibold">{q.siteName}</p><p className="text-xs text-slate-500">{q.clientName}</p></td><td className="px-5 py-4 text-xs"><p>{date(q.issueDate)}</p><p className="mt-1 text-slate-500">to {date(q.validUntil)}</p></td><td className="px-5 py-4 text-right font-bold">{money.format(q.totalAmount)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${colors[q.status]||colors.DRAFT}`}>{q.status}</span></td><td className="px-5 py-4 text-right"><button onClick={()=>setSelected(q)} className="rounded-md border px-3 py-2 text-xs font-bold text-indigo-700">View / Print</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-14 text-center text-sm text-slate-500">No quotations found. Create your first site work quotation.</div>}</section>}
  {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4 print:static print:bg-white print:p-0"><div className="mx-auto max-w-4xl rounded-xl bg-white shadow-2xl print:max-w-none print:shadow-none"><div className="flex items-center justify-between border-b p-4 print:hidden"><select value={selected.status} onChange={e=>setQuotationStatus(selected,e.target.value)} className="rounded-md border px-3 py-2 text-sm">{["DRAFT","SENT","ACCEPTED","REJECTED","EXPIRED"].map(s=><option key={s}>{s}</option>)}</select><div className="flex gap-2"><button onClick={()=>window.print()} className="rounded-md bg-indigo-700 px-4 py-2 text-sm font-bold text-white">Print / Save PDF</button><button onClick={()=>setSelected(null)} className="rounded-md border px-4 py-2 text-sm">Close</button></div></div>
   <article className="p-10 text-slate-900"><header className="flex justify-between border-b-2 border-indigo-700 pb-6"><div><h1 className="text-3xl font-black tracking-wide text-indigo-800">QUOTATION</h1><p className="mt-2 text-sm font-bold">{selected.quotationNumber}</p></div><div className="text-right text-sm"><p><b>Date:</b> {date(selected.issueDate)}</p><p className="mt-1"><b>Valid until:</b> {date(selected.validUntil)}</p></div></header><div className="my-6 grid grid-cols-2 gap-8 text-sm"><div><p className="text-xs font-bold uppercase text-slate-400">Quotation for</p><p className="mt-2 text-lg font-bold">{selected.clientName}</p><p>{selected.siteName} {selected.siteCode&&`(${selected.siteCode})`}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Subject</p><p className="mt-2 font-semibold">{selected.subject}</p></div></div>
   <table className="w-full border-collapse text-sm"><thead><tr className="bg-indigo-700 text-white"><th className="border p-3 text-left">#</th><th className="border p-3 text-left">Description</th><th className="border p-3">Unit</th><th className="border p-3 text-right">Qty</th><th className="border p-3 text-right">Rate</th><th className="border p-3 text-right">Amount</th></tr></thead><tbody>{selected.items.map((i,n)=><tr key={n}><td className="border p-3">{n+1}</td><td className="border p-3">{i.description}</td><td className="border p-3 text-center">{i.unit}</td><td className="border p-3 text-right">{i.quantity}</td><td className="border p-3 text-right">{money.format(i.rate)}</td><td className="border p-3 text-right font-semibold">{money.format(i.amount)}</td></tr>)}</tbody></table>
   <div className="ml-auto mt-5 w-80 space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{money.format(selected.subtotal)}</b></div>{selected.discountAmount>0&&<div className="flex justify-between"><span>Discount ({selected.discountPercent}%)</span><b>- {money.format(selected.discountAmount)}</b></div>}<div className="flex justify-between"><span>GST ({selected.gstPercent}%)</span><b>{money.format(selected.gstAmount)}</b></div><div className="flex justify-between border-t-2 pt-3 text-lg text-indigo-800"><span className="font-bold">Grand Total</span><b>{money.format(selected.totalAmount)}</b></div></div>
   {(selected.notes||selected.terms)&&<div className="mt-8 grid gap-5 border-t pt-5 text-xs sm:grid-cols-2">{selected.notes&&<div><b>Notes</b><p className="mt-2 whitespace-pre-wrap text-slate-600">{selected.notes}</p></div>}{selected.terms&&<div><b>Terms & Conditions</b><p className="mt-2 whitespace-pre-wrap text-slate-600">{selected.terms}</p></div>}</div>}<div className="mt-16 text-right text-sm font-bold">Authorised Signatory</div></article>
  </div></div>}
 </main></div></div>
}
