import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "./components/toast-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col"><script dangerouslySetInnerHTML={{ __html: "try { const dark = localStorage.getItem(\u0027kinetic-theme\u0027) === \u0027dark\u0027; document.documentElement.classList.toggle(\u0027dark\u0027, dark); document.documentElement.dataset.theme = dark ? \u0027dark\u0027 : \u0027light\u0027 } catch {}" }} /><ToastProvider>{children}</ToastProvider></body>
    </html>
  );
}
